/* Generated by Nim Compiler v1.0.6 */
/*   (c) 2019 Andreas Rumpf */
/* The generated code is subject to the original license. */
#define NIM_INTBITS 64

#include "nimbase.h"
#undef LANGUAGE_C
#undef MIPSEB
#undef MIPSEL
#undef PPC
#undef R3000
#undef R4000
#undef i386
#undef linux
#undef mips
#undef near
#undef far
#undef powerpc
#undef unix
#define nimfr_(x, y)
#define nimln_(x, y)
typedef struct tyObject_JNIInvokeInterface__BH89cWeWlOVoMyLmwNaDn1Q tyObject_JNIInvokeInterface__BH89cWeWlOVoMyLmwNaDn1Q;
typedef struct tyObject_JavaVMInitArgs__cKymzNrkoBnuXJDMMaEfiA tyObject_JavaVMInitArgs__cKymzNrkoBnuXJDMMaEfiA;
typedef struct TNimType TNimType;
typedef struct TNimNode TNimNode;
typedef struct tyObject_jobject_base__jOmBXO3N5WagCUVjVXS9bwQ tyObject_jobject_base__jOmBXO3N5WagCUVjVXS9bwQ;
typedef struct tyObject_JClasscolonObjectType___OX6jzfCvSDx9bg2iJ4S6u5Q tyObject_JClasscolonObjectType___OX6jzfCvSDx9bg2iJ4S6u5Q;
typedef N_CDECL_PTR(NI32, tyProc__VeWZhCOugPV742UOEm7dbg) (tyObject_JNIInvokeInterface__BH89cWeWlOVoMyLmwNaDn1Q*** pvm, void** penv, void* args);
typedef N_CDECL_PTR(NI32, tyProc__I3c9az5111PCFEMM1gYcH1A) (tyObject_JavaVMInitArgs__cKymzNrkoBnuXJDMMaEfiA* vm_args);
typedef N_CDECL_PTR(NI32, tyProc__YrUoJ6tyx2AIkIhA9celD0Q) (tyObject_JNIInvokeInterface__BH89cWeWlOVoMyLmwNaDn1Q*** vmBuf, NI32 bufLen, NI32* nVMs);
typedef N_CDECL_PTR(NI32, tyProc__RfWjXps9aotGZt9ckVYiIncw) (tyObject_JNIInvokeInterface__BH89cWeWlOVoMyLmwNaDn1Q** vm);
typedef N_CDECL_PTR(NI32, tyProc__UtsYl9csBBW9bDeClhcQr8tw) (tyObject_JNIInvokeInterface__BH89cWeWlOVoMyLmwNaDn1Q** vm, void** penv, void* args);
typedef N_CDECL_PTR(NI32, tyProc__9cKk9brklU6KpiJr5q23rEZw) (tyObject_JNIInvokeInterface__BH89cWeWlOVoMyLmwNaDn1Q** vm, void** penv, NI32 version);
struct tyObject_JNIInvokeInterface__BH89cWeWlOVoMyLmwNaDn1Q {
void* reserved0;
void* reserved1;
void* reserved2;
tyProc__RfWjXps9aotGZt9ckVYiIncw DestroyJavaVM;
tyProc__UtsYl9csBBW9bDeClhcQr8tw AttachCurrentThread;
tyProc__RfWjXps9aotGZt9ckVYiIncw DetachCurrentThread;
tyProc__9cKk9brklU6KpiJr5q23rEZw GetEnv;
tyProc__UtsYl9csBBW9bDeClhcQr8tw AttachCurrentThreadAsDaemon;
};
typedef NU8 tyEnum_TNimKind__jIBKr1ejBgsfM33Kxw4j7A;
typedef NU8 tySet_tyEnum_TNimTypeFlag__v8QUszD1sWlSIWZz7mC4bQ;
typedef N_NIMCALL_PTR(void, tyProc__ojoeKfW4VYIm36I9cpDTQIg) (void* p, NI op);
typedef N_NIMCALL_PTR(void*, tyProc__WSm2xU5ARYv9aAR4l0z9c9auQ) (void* p);
struct TNimType {
NI size;
tyEnum_TNimKind__jIBKr1ejBgsfM33Kxw4j7A kind;
tySet_tyEnum_TNimTypeFlag__v8QUszD1sWlSIWZz7mC4bQ flags;
TNimType* base;
TNimNode* node;
void* finalizer;
tyProc__ojoeKfW4VYIm36I9cpDTQIg marker;
tyProc__WSm2xU5ARYv9aAR4l0z9c9auQ deepcopy;
};
typedef NU8 tyEnum_TNimNodeKind__unfNsxrcATrufDZmpBq4HQ;
struct TNimNode {
tyEnum_TNimNodeKind__unfNsxrcATrufDZmpBq4HQ kind;
NI offset;
TNimType* typ;
NCSTRING name;
NI len;
TNimNode** sons;
};
struct tyObject_jobject_base__jOmBXO3N5WagCUVjVXS9bwQ {
char dummy;
};
struct tyObject_JClasscolonObjectType___OX6jzfCvSDx9bg2iJ4S6u5Q {
  tyObject_jobject_base__jOmBXO3N5WagCUVjVXS9bwQ Sup;
};
tyProc__VeWZhCOugPV742UOEm7dbg JNI_CreateJavaVM__JtrSv0NNKo8S2XKSj5JUEA;
tyProc__I3c9az5111PCFEMM1gYcH1A JNI_GetDefaultJavaVMInitArgs__vGe5z1qA6HlNq0gvaRLF8w;
tyProc__YrUoJ6tyx2AIkIhA9celD0Q JNI_GetCreatedJavaVMs__p1eaEgr9cGNRGolefCPJoNw;
TNimType NTI__BH89cWeWlOVoMyLmwNaDn1Q_;
extern TNimType NTI__vr5DoT1jILTGdRlYv1OYpw_;
TNimType NTI__RfWjXps9aotGZt9ckVYiIncw_;
TNimType NTI__UtsYl9csBBW9bDeClhcQr8tw_;
TNimType NTI__9cKk9brklU6KpiJr5q23rEZw_;
TNimType NTI__tnOVALla2cpARCc1vlNXJg_;
TNimType NTI__7FcdJ3hvYzGh4dRoLuZvAQ_;
TNimType NTI__jOmBXO3N5WagCUVjVXS9bwQ_;
TNimType NTI__OX6jzfCvSDx9bg2iJ4S6u5Q_;
TNimType NTI__rVVcaWnYpyCHyliNE2pmHQ_;
TNimType NTI__pPa0PUyylMh9adAOVkZUkLA_;
N_LIB_PRIVATE N_NIMCALL(void, unknown_jni_wrapperDatInit000)(void) {
static TNimNode* TM__hA9bTqZsbgbwXWDrK8VWOxw_2_8[8];
static TNimNode TM__hA9bTqZsbgbwXWDrK8VWOxw_0[11];
NTI__BH89cWeWlOVoMyLmwNaDn1Q_.size = sizeof(tyObject_JNIInvokeInterface__BH89cWeWlOVoMyLmwNaDn1Q);
NTI__BH89cWeWlOVoMyLmwNaDn1Q_.kind = 18;
NTI__BH89cWeWlOVoMyLmwNaDn1Q_.base = 0;
NTI__BH89cWeWlOVoMyLmwNaDn1Q_.flags = 3;
TM__hA9bTqZsbgbwXWDrK8VWOxw_2_8[0] = &TM__hA9bTqZsbgbwXWDrK8VWOxw_0[1];
TM__hA9bTqZsbgbwXWDrK8VWOxw_0[1].kind = 1;
TM__hA9bTqZsbgbwXWDrK8VWOxw_0[1].offset = offsetof(tyObject_JNIInvokeInterface__BH89cWeWlOVoMyLmwNaDn1Q, reserved0);
TM__hA9bTqZsbgbwXWDrK8VWOxw_0[1].typ = (&NTI__vr5DoT1jILTGdRlYv1OYpw_);
TM__hA9bTqZsbgbwXWDrK8VWOxw_0[1].name = "reserved0";
TM__hA9bTqZsbgbwXWDrK8VWOxw_2_8[1] = &TM__hA9bTqZsbgbwXWDrK8VWOxw_0[2];
TM__hA9bTqZsbgbwXWDrK8VWOxw_0[2].kind = 1;
TM__hA9bTqZsbgbwXWDrK8VWOxw_0[2].offset = offsetof(tyObject_JNIInvokeInterface__BH89cWeWlOVoMyLmwNaDn1Q, reserved1);
TM__hA9bTqZsbgbwXWDrK8VWOxw_0[2].typ = (&NTI__vr5DoT1jILTGdRlYv1OYpw_);
TM__hA9bTqZsbgbwXWDrK8VWOxw_0[2].name = "reserved1";
TM__hA9bTqZsbgbwXWDrK8VWOxw_2_8[2] = &TM__hA9bTqZsbgbwXWDrK8VWOxw_0[3];
TM__hA9bTqZsbgbwXWDrK8VWOxw_0[3].kind = 1;
TM__hA9bTqZsbgbwXWDrK8VWOxw_0[3].offset = offsetof(tyObject_JNIInvokeInterface__BH89cWeWlOVoMyLmwNaDn1Q, reserved2);
TM__hA9bTqZsbgbwXWDrK8VWOxw_0[3].typ = (&NTI__vr5DoT1jILTGdRlYv1OYpw_);
TM__hA9bTqZsbgbwXWDrK8VWOxw_0[3].name = "reserved2";
TM__hA9bTqZsbgbwXWDrK8VWOxw_2_8[3] = &TM__hA9bTqZsbgbwXWDrK8VWOxw_0[4];
NTI__RfWjXps9aotGZt9ckVYiIncw_.size = sizeof(tyProc__RfWjXps9aotGZt9ckVYiIncw);
NTI__RfWjXps9aotGZt9ckVYiIncw_.kind = 25;
NTI__RfWjXps9aotGZt9ckVYiIncw_.base = 0;
NTI__RfWjXps9aotGZt9ckVYiIncw_.flags = 3;
TM__hA9bTqZsbgbwXWDrK8VWOxw_0[4].kind = 1;
TM__hA9bTqZsbgbwXWDrK8VWOxw_0[4].offset = offsetof(tyObject_JNIInvokeInterface__BH89cWeWlOVoMyLmwNaDn1Q, DestroyJavaVM);
TM__hA9bTqZsbgbwXWDrK8VWOxw_0[4].typ = (&NTI__RfWjXps9aotGZt9ckVYiIncw_);
TM__hA9bTqZsbgbwXWDrK8VWOxw_0[4].name = "DestroyJavaVM";
TM__hA9bTqZsbgbwXWDrK8VWOxw_2_8[4] = &TM__hA9bTqZsbgbwXWDrK8VWOxw_0[5];
NTI__UtsYl9csBBW9bDeClhcQr8tw_.size = sizeof(tyProc__UtsYl9csBBW9bDeClhcQr8tw);
NTI__UtsYl9csBBW9bDeClhcQr8tw_.kind = 25;
NTI__UtsYl9csBBW9bDeClhcQr8tw_.base = 0;
NTI__UtsYl9csBBW9bDeClhcQr8tw_.flags = 3;
TM__hA9bTqZsbgbwXWDrK8VWOxw_0[5].kind = 1;
TM__hA9bTqZsbgbwXWDrK8VWOxw_0[5].offset = offsetof(tyObject_JNIInvokeInterface__BH89cWeWlOVoMyLmwNaDn1Q, AttachCurrentThread);
TM__hA9bTqZsbgbwXWDrK8VWOxw_0[5].typ = (&NTI__UtsYl9csBBW9bDeClhcQr8tw_);
TM__hA9bTqZsbgbwXWDrK8VWOxw_0[5].name = "AttachCurrentThread";
TM__hA9bTqZsbgbwXWDrK8VWOxw_2_8[5] = &TM__hA9bTqZsbgbwXWDrK8VWOxw_0[6];
TM__hA9bTqZsbgbwXWDrK8VWOxw_0[6].kind = 1;
TM__hA9bTqZsbgbwXWDrK8VWOxw_0[6].offset = offsetof(tyObject_JNIInvokeInterface__BH89cWeWlOVoMyLmwNaDn1Q, DetachCurrentThread);
TM__hA9bTqZsbgbwXWDrK8VWOxw_0[6].typ = (&NTI__RfWjXps9aotGZt9ckVYiIncw_);
TM__hA9bTqZsbgbwXWDrK8VWOxw_0[6].name = "DetachCurrentThread";
TM__hA9bTqZsbgbwXWDrK8VWOxw_2_8[6] = &TM__hA9bTqZsbgbwXWDrK8VWOxw_0[7];
NTI__9cKk9brklU6KpiJr5q23rEZw_.size = sizeof(tyProc__9cKk9brklU6KpiJr5q23rEZw);
NTI__9cKk9brklU6KpiJr5q23rEZw_.kind = 25;
NTI__9cKk9brklU6KpiJr5q23rEZw_.base = 0;
NTI__9cKk9brklU6KpiJr5q23rEZw_.flags = 3;
TM__hA9bTqZsbgbwXWDrK8VWOxw_0[7].kind = 1;
TM__hA9bTqZsbgbwXWDrK8VWOxw_0[7].offset = offsetof(tyObject_JNIInvokeInterface__BH89cWeWlOVoMyLmwNaDn1Q, GetEnv);
TM__hA9bTqZsbgbwXWDrK8VWOxw_0[7].typ = (&NTI__9cKk9brklU6KpiJr5q23rEZw_);
TM__hA9bTqZsbgbwXWDrK8VWOxw_0[7].name = "GetEnv";
TM__hA9bTqZsbgbwXWDrK8VWOxw_2_8[7] = &TM__hA9bTqZsbgbwXWDrK8VWOxw_0[8];
TM__hA9bTqZsbgbwXWDrK8VWOxw_0[8].kind = 1;
TM__hA9bTqZsbgbwXWDrK8VWOxw_0[8].offset = offsetof(tyObject_JNIInvokeInterface__BH89cWeWlOVoMyLmwNaDn1Q, AttachCurrentThreadAsDaemon);
TM__hA9bTqZsbgbwXWDrK8VWOxw_0[8].typ = (&NTI__UtsYl9csBBW9bDeClhcQr8tw_);
TM__hA9bTqZsbgbwXWDrK8VWOxw_0[8].name = "AttachCurrentThreadAsDaemon";
TM__hA9bTqZsbgbwXWDrK8VWOxw_0[0].len = 8; TM__hA9bTqZsbgbwXWDrK8VWOxw_0[0].kind = 2; TM__hA9bTqZsbgbwXWDrK8VWOxw_0[0].sons = &TM__hA9bTqZsbgbwXWDrK8VWOxw_2_8[0];
NTI__BH89cWeWlOVoMyLmwNaDn1Q_.node = &TM__hA9bTqZsbgbwXWDrK8VWOxw_0[0];
NTI__tnOVALla2cpARCc1vlNXJg_.size = sizeof(tyObject_JNIInvokeInterface__BH89cWeWlOVoMyLmwNaDn1Q*);
NTI__tnOVALla2cpARCc1vlNXJg_.kind = 21;
NTI__tnOVALla2cpARCc1vlNXJg_.base = (&NTI__BH89cWeWlOVoMyLmwNaDn1Q_);
NTI__tnOVALla2cpARCc1vlNXJg_.flags = 3;
NTI__7FcdJ3hvYzGh4dRoLuZvAQ_.size = sizeof(tyObject_JNIInvokeInterface__BH89cWeWlOVoMyLmwNaDn1Q**);
NTI__7FcdJ3hvYzGh4dRoLuZvAQ_.kind = 21;
NTI__7FcdJ3hvYzGh4dRoLuZvAQ_.base = (&NTI__tnOVALla2cpARCc1vlNXJg_);
NTI__7FcdJ3hvYzGh4dRoLuZvAQ_.flags = 3;
NTI__jOmBXO3N5WagCUVjVXS9bwQ_.size = sizeof(tyObject_jobject_base__jOmBXO3N5WagCUVjVXS9bwQ);
NTI__jOmBXO3N5WagCUVjVXS9bwQ_.kind = 18;
NTI__jOmBXO3N5WagCUVjVXS9bwQ_.base = 0;
NTI__jOmBXO3N5WagCUVjVXS9bwQ_.flags = 1;
TM__hA9bTqZsbgbwXWDrK8VWOxw_0[9].len = 0; TM__hA9bTqZsbgbwXWDrK8VWOxw_0[9].kind = 2;
NTI__jOmBXO3N5WagCUVjVXS9bwQ_.node = &TM__hA9bTqZsbgbwXWDrK8VWOxw_0[9];
NTI__OX6jzfCvSDx9bg2iJ4S6u5Q_.size = sizeof(tyObject_JClasscolonObjectType___OX6jzfCvSDx9bg2iJ4S6u5Q);
NTI__OX6jzfCvSDx9bg2iJ4S6u5Q_.kind = 18;
NTI__OX6jzfCvSDx9bg2iJ4S6u5Q_.base = (&NTI__jOmBXO3N5WagCUVjVXS9bwQ_);
NTI__OX6jzfCvSDx9bg2iJ4S6u5Q_.flags = 1;
TM__hA9bTqZsbgbwXWDrK8VWOxw_0[10].len = 0; TM__hA9bTqZsbgbwXWDrK8VWOxw_0[10].kind = 2;
NTI__OX6jzfCvSDx9bg2iJ4S6u5Q_.node = &TM__hA9bTqZsbgbwXWDrK8VWOxw_0[10];
NTI__rVVcaWnYpyCHyliNE2pmHQ_.size = sizeof(tyObject_JClasscolonObjectType___OX6jzfCvSDx9bg2iJ4S6u5Q*);
NTI__rVVcaWnYpyCHyliNE2pmHQ_.kind = 21;
NTI__rVVcaWnYpyCHyliNE2pmHQ_.base = (&NTI__OX6jzfCvSDx9bg2iJ4S6u5Q_);
NTI__rVVcaWnYpyCHyliNE2pmHQ_.flags = 3;
NTI__pPa0PUyylMh9adAOVkZUkLA_.size = sizeof(tyObject_jobject_base__jOmBXO3N5WagCUVjVXS9bwQ*);
NTI__pPa0PUyylMh9adAOVkZUkLA_.kind = 21;
NTI__pPa0PUyylMh9adAOVkZUkLA_.base = (&NTI__jOmBXO3N5WagCUVjVXS9bwQ_);
NTI__pPa0PUyylMh9adAOVkZUkLA_.flags = 3;
}

