/* Generated by Nim Compiler v1.0.6 */
/*   (c) 2019 Andreas Rumpf */
/* The generated code is subject to the original license. */
#define NIM_INTBITS 32

#include "nimbase.h"
#include <sys/types.h>
#include <string.h>
#include <android/log.h>
#include <math.h>
#define _GNU_SOURCE
#include <pthread.h>
#undef LANGUAGE_C
#undef MIPSEB
#undef MIPSEL
#undef PPC
#undef R3000
#undef R4000
#undef i386
#undef linux
#undef mips
#undef near
#undef far
#undef powerpc
#undef unix
#define nimfr_(x, y)
#define nimln_(x, y)
typedef struct tyObject_TickContext__1qtOMRK8IluFHXVmNYGT9cw tyObject_TickContext__1qtOMRK8IluFHXVmNYGT9cw;
typedef struct tyObject_JNIInvokeInterface__BH89cWeWlOVoMyLmwNaDn1Q tyObject_JNIInvokeInterface__BH89cWeWlOVoMyLmwNaDn1Q;
typedef struct tyObject_JClasscolonObjectType___OX6jzfCvSDx9bg2iJ4S6u5Q tyObject_JClasscolonObjectType___OX6jzfCvSDx9bg2iJ4S6u5Q;
typedef struct tyObject_jobject_base__jOmBXO3N5WagCUVjVXS9bwQ tyObject_jobject_base__jOmBXO3N5WagCUVjVXS9bwQ;
typedef struct tyObject_Thread__gtP9c8k5UKzYjkZfEnGNYRg tyObject_Thread__gtP9c8k5UKzYjkZfEnGNYRg;
typedef struct tyObject_GcThread__hgJQSlfXDOK3SwSHjeZBXg tyObject_GcThread__hgJQSlfXDOK3SwSHjeZBXg;
typedef struct tyObject_jstringcolonObjectType___pIwvSfG0x9ct585jz20sNPg tyObject_jstringcolonObjectType___pIwvSfG0x9ct585jz20sNPg;
typedef struct tyObject_JNINativeInterface__sVC60arJvSJ44y0t2XTqiw tyObject_JNINativeInterface__sVC60arJvSJ44y0t2XTqiw;
typedef struct NimStringDesc NimStringDesc;
typedef struct TGenericSeq TGenericSeq;
typedef struct tyObject_jthrowablecolonObjectType___evWc9b49biOgNwOnXGhS2vGA tyObject_jthrowablecolonObjectType___evWc9b49biOgNwOnXGhS2vGA;
typedef union tyObject_jvalue__QCDTMcqbrVjxIcGFMr9ai9cg tyObject_jvalue__QCDTMcqbrVjxIcGFMr9ai9cg;
typedef struct tyObject_jarraycolonObjectType___RmEW8whL9cBQ8DcJ70FJ6lg tyObject_jarraycolonObjectType___RmEW8whL9cBQ8DcJ70FJ6lg;
typedef struct tyObject_jtypedArraycolonObjectType___a9auPON3XaqaXTm9cPqxlt9aw tyObject_jtypedArraycolonObjectType___a9auPON3XaqaXTm9cPqxlt9aw;
typedef struct tyObject_JNINativeMethod__L6bdxAULUoPq6MmpjHdhEA tyObject_JNINativeMethod__L6bdxAULUoPq6MmpjHdhEA;
typedef struct TNimType TNimType;
typedef struct TNimNode TNimNode;
typedef N_NIMCALL_PTR(void, tyProc__v2sqjMSLaPokKgjL7ewsxw) (tyObject_TickContext__1qtOMRK8IluFHXVmNYGT9cw* m);
struct tyObject_Thread__gtP9c8k5UKzYjkZfEnGNYRg {
tyObject_GcThread__hgJQSlfXDOK3SwSHjeZBXg* core;
pthread_t sys;
tyProc__v2sqjMSLaPokKgjL7ewsxw dataFn;
tyObject_TickContext__1qtOMRK8IluFHXVmNYGT9cw* data;
};
struct tyObject_TickContext__1qtOMRK8IluFHXVmNYGT9cw {
tyObject_JNIInvokeInterface__BH89cWeWlOVoMyLmwNaDn1Q** javaVM;
tyObject_JClasscolonObjectType___OX6jzfCvSDx9bg2iJ4S6u5Q* jniHelperClz;
tyObject_jobject_base__jOmBXO3N5WagCUVjVXS9bwQ* jniHelperObj;
tyObject_JClasscolonObjectType___OX6jzfCvSDx9bg2iJ4S6u5Q* mainActivityClz;
tyObject_jobject_base__jOmBXO3N5WagCUVjVXS9bwQ* mainActivityObj;
tyObject_Thread__gtP9c8k5UKzYjkZfEnGNYRg thrd;
NI done;
};
struct TGenericSeq {
NI len;
NI reserved;
};
struct NimStringDesc {
  TGenericSeq Sup;
NIM_CHAR data[SEQ_DECL_SIZE];
};
struct tyObject_jobject_base__jOmBXO3N5WagCUVjVXS9bwQ {
char dummy;
};
struct tyObject_jstringcolonObjectType___pIwvSfG0x9ct585jz20sNPg {
  tyObject_jobject_base__jOmBXO3N5WagCUVjVXS9bwQ Sup;
};
typedef N_CDECL_PTR(NI32, tyProc__GTiyzoLqRtZelJ9cswu7Uow) (tyObject_JNINativeInterface__sVC60arJvSJ44y0t2XTqiw** env);
typedef N_CDECL_PTR(tyObject_JClasscolonObjectType___OX6jzfCvSDx9bg2iJ4S6u5Q*, tyProc__DFZxGxC0ZHf9bsKfZXJiERg) (tyObject_JNINativeInterface__sVC60arJvSJ44y0t2XTqiw** env, NCSTRING name, tyObject_jobject_base__jOmBXO3N5WagCUVjVXS9bwQ* loader, NI8* buf, NI32 len);
typedef N_CDECL_PTR(tyObject_JClasscolonObjectType___OX6jzfCvSDx9bg2iJ4S6u5Q*, tyProc__em7j1GBs7VNAXMH7F9bsLzA) (tyObject_JNINativeInterface__sVC60arJvSJ44y0t2XTqiw** env, NCSTRING name);
typedef N_CDECL_PTR(void*, tyProc__RI5QcbnF5rKJCpfe5tSkuw) (tyObject_JNINativeInterface__sVC60arJvSJ44y0t2XTqiw** env, tyObject_jobject_base__jOmBXO3N5WagCUVjVXS9bwQ* meth);
typedef N_CDECL_PTR(tyObject_jobject_base__jOmBXO3N5WagCUVjVXS9bwQ*, tyProc__6GaozS8Gb3Dr0wKgiJkjkQ) (tyObject_JNINativeInterface__sVC60arJvSJ44y0t2XTqiw** env, tyObject_JClasscolonObjectType___OX6jzfCvSDx9bg2iJ4S6u5Q* cls, void* methodID, NU8 isStatic);
typedef N_CDECL_PTR(tyObject_JClasscolonObjectType___OX6jzfCvSDx9bg2iJ4S6u5Q*, tyProc__VWJPYSlzvPXlCZ6l3afNaA) (tyObject_JNINativeInterface__sVC60arJvSJ44y0t2XTqiw** env, tyObject_JClasscolonObjectType___OX6jzfCvSDx9bg2iJ4S6u5Q* sub);
typedef N_CDECL_PTR(NU8, tyProc__4CPVQiZTL1EgQ5WgxnZgfQ) (tyObject_JNINativeInterface__sVC60arJvSJ44y0t2XTqiw** env, tyObject_JClasscolonObjectType___OX6jzfCvSDx9bg2iJ4S6u5Q* sub, tyObject_JClasscolonObjectType___OX6jzfCvSDx9bg2iJ4S6u5Q* sup);
typedef N_CDECL_PTR(NI32, tyProc__iJRdrCdAU19cu9cNbozr6Lww) (tyObject_JNINativeInterface__sVC60arJvSJ44y0t2XTqiw** env, tyObject_jthrowablecolonObjectType___evWc9b49biOgNwOnXGhS2vGA* obj);
typedef N_CDECL_PTR(NI32, tyProc__8haEwIKzLtY9ahp2OaQCKPA) (tyObject_JNINativeInterface__sVC60arJvSJ44y0t2XTqiw** env, tyObject_JClasscolonObjectType___OX6jzfCvSDx9bg2iJ4S6u5Q* clazz, NCSTRING msg);
typedef N_CDECL_PTR(tyObject_jthrowablecolonObjectType___evWc9b49biOgNwOnXGhS2vGA*, tyProc__PA9cdiVOg516By6pGvaQWxw) (tyObject_JNINativeInterface__sVC60arJvSJ44y0t2XTqiw** env);
typedef N_CDECL_PTR(void, tyProc__TFdHnXCI9aRT5twkNf9boeCQ) (tyObject_JNINativeInterface__sVC60arJvSJ44y0t2XTqiw** env);
typedef N_CDECL_PTR(void, tyProc__zprQk8MzhuZuCVVfs7nzAQ) (tyObject_JNINativeInterface__sVC60arJvSJ44y0t2XTqiw** env, NCSTRING msg);
typedef N_CDECL_PTR(NI32, tyProc__bHzJcWtjDNDl5kZqzPrAZA) (tyObject_JNINativeInterface__sVC60arJvSJ44y0t2XTqiw** env, NI32 capacity);
typedef N_CDECL_PTR(tyObject_jobject_base__jOmBXO3N5WagCUVjVXS9bwQ*, tyProc__9aa48FNC3q6O6o7JxBTqyIg) (tyObject_JNINativeInterface__sVC60arJvSJ44y0t2XTqiw** env, tyObject_jobject_base__jOmBXO3N5WagCUVjVXS9bwQ* res);
typedef N_CDECL_PTR(void, tyProc__g66UlTcFcTsHnYKbhCcgkQ) (tyObject_JNINativeInterface__sVC60arJvSJ44y0t2XTqiw** env, tyObject_jobject_base__jOmBXO3N5WagCUVjVXS9bwQ* obj);
typedef N_CDECL_PTR(NU8, tyProc__bOP4TXpDkCCdPUdwBShcHg) (tyObject_JNINativeInterface__sVC60arJvSJ44y0t2XTqiw** env, tyObject_jobject_base__jOmBXO3N5WagCUVjVXS9bwQ* obj1, tyObject_jobject_base__jOmBXO3N5WagCUVjVXS9bwQ* obj2);
typedef N_CDECL_PTR(tyObject_jobject_base__jOmBXO3N5WagCUVjVXS9bwQ*, tyProc__JzQGCKUL8PcNxxx7x5sbnQ) (tyObject_JNINativeInterface__sVC60arJvSJ44y0t2XTqiw** env, tyObject_JClasscolonObjectType___OX6jzfCvSDx9bg2iJ4S6u5Q* clazz);
typedef N_CDECL_PTR(tyObject_jobject_base__jOmBXO3N5WagCUVjVXS9bwQ*, tyProc__xDGZyxEkNgFs49a0XpRnqkw) (tyObject_JNINativeInterface__sVC60arJvSJ44y0t2XTqiw** env, tyObject_JClasscolonObjectType___OX6jzfCvSDx9bg2iJ4S6u5Q* clazz, void* methodID, ...);
typedef N_CDECL_PTR(tyObject_jobject_base__jOmBXO3N5WagCUVjVXS9bwQ*, tyProc__etz1nMATyY52waZ3IHPvNA) (tyObject_JNINativeInterface__sVC60arJvSJ44y0t2XTqiw** env, tyObject_JClasscolonObjectType___OX6jzfCvSDx9bg2iJ4S6u5Q* clazz, void* methodID, tyObject_jvalue__QCDTMcqbrVjxIcGFMr9ai9cg* args);
typedef N_CDECL_PTR(tyObject_JClasscolonObjectType___OX6jzfCvSDx9bg2iJ4S6u5Q*, tyProc__7siyna4EZ2o31AWmBTAyeQ) (tyObject_JNINativeInterface__sVC60arJvSJ44y0t2XTqiw** env, tyObject_jobject_base__jOmBXO3N5WagCUVjVXS9bwQ* obj);
typedef N_CDECL_PTR(NU8, tyProc__Gpd9aw5aWm5w1vetb49cc9cbA) (tyObject_JNINativeInterface__sVC60arJvSJ44y0t2XTqiw** env, tyObject_jobject_base__jOmBXO3N5WagCUVjVXS9bwQ* obj, tyObject_JClasscolonObjectType___OX6jzfCvSDx9bg2iJ4S6u5Q* clazz);
typedef N_CDECL_PTR(void*, tyProc__SJltzEg0qYejYe9c9cKJtVhg) (tyObject_JNINativeInterface__sVC60arJvSJ44y0t2XTqiw** env, tyObject_JClasscolonObjectType___OX6jzfCvSDx9bg2iJ4S6u5Q* clazz, NCSTRING name, NCSTRING sig);
typedef N_CDECL_PTR(tyObject_jobject_base__jOmBXO3N5WagCUVjVXS9bwQ*, tyProc__URa83EjSMygGDUgxAj7NJA) (tyObject_JNINativeInterface__sVC60arJvSJ44y0t2XTqiw** env, tyObject_jobject_base__jOmBXO3N5WagCUVjVXS9bwQ* obj, void* methodID, ...);
typedef N_CDECL_PTR(tyObject_jobject_base__jOmBXO3N5WagCUVjVXS9bwQ*, tyProc__73B0l7AF0UoF9c4pPSoPTtQ) (tyObject_JNINativeInterface__sVC60arJvSJ44y0t2XTqiw** env, tyObject_jobject_base__jOmBXO3N5WagCUVjVXS9bwQ* obj, void* methodID, tyObject_jvalue__QCDTMcqbrVjxIcGFMr9ai9cg* args);
typedef N_CDECL_PTR(NU8, tyProc__BzA25CAZLkmSibqrGJQJRw) (tyObject_JNINativeInterface__sVC60arJvSJ44y0t2XTqiw** env, tyObject_jobject_base__jOmBXO3N5WagCUVjVXS9bwQ* obj, void* methodID, ...);
typedef N_CDECL_PTR(NU8, tyProc__h0HQthcF0bCGXZqy9cjpTqw) (tyObject_JNINativeInterface__sVC60arJvSJ44y0t2XTqiw** env, tyObject_jobject_base__jOmBXO3N5WagCUVjVXS9bwQ* obj, void* methodID, tyObject_jvalue__QCDTMcqbrVjxIcGFMr9ai9cg* args);
typedef N_CDECL_PTR(NI8, tyProc__dg2OkZ2plylt11Mvu1y1rg) (tyObject_JNINativeInterface__sVC60arJvSJ44y0t2XTqiw** env, tyObject_jobject_base__jOmBXO3N5WagCUVjVXS9bwQ* obj, void* methodID, ...);
typedef N_CDECL_PTR(NI8, tyProc__t9b0wgXJxuXOxUZ7eVy24Lw) (tyObject_JNINativeInterface__sVC60arJvSJ44y0t2XTqiw** env, tyObject_jobject_base__jOmBXO3N5WagCUVjVXS9bwQ* obj, void* methodID, tyObject_jvalue__QCDTMcqbrVjxIcGFMr9ai9cg* args);
typedef N_CDECL_PTR(NU16, tyProc__sukDG9ctV6DmP4uGvm9bg73Q) (tyObject_JNINativeInterface__sVC60arJvSJ44y0t2XTqiw** env, tyObject_jobject_base__jOmBXO3N5WagCUVjVXS9bwQ* obj, void* methodID, ...);
typedef N_CDECL_PTR(NU16, tyProc__WTPd4nGpA9bMpOX9cuVNdWng) (tyObject_JNINativeInterface__sVC60arJvSJ44y0t2XTqiw** env, tyObject_jobject_base__jOmBXO3N5WagCUVjVXS9bwQ* obj, void* methodID, tyObject_jvalue__QCDTMcqbrVjxIcGFMr9ai9cg* args);
typedef N_CDECL_PTR(NI16, tyProc__ysjVE7f0HAax7bq4l7H2sw) (tyObject_JNINativeInterface__sVC60arJvSJ44y0t2XTqiw** env, tyObject_jobject_base__jOmBXO3N5WagCUVjVXS9bwQ* obj, void* methodID, ...);
typedef N_CDECL_PTR(NI16, tyProc__8ZgUh9bmR8aEVUx9bRfh4E4g) (tyObject_JNINativeInterface__sVC60arJvSJ44y0t2XTqiw** env, tyObject_jobject_base__jOmBXO3N5WagCUVjVXS9bwQ* obj, void* methodID, tyObject_jvalue__QCDTMcqbrVjxIcGFMr9ai9cg* args);
typedef N_CDECL_PTR(NI32, tyProc__RebaplENYTeDvBpbs8enhQ) (tyObject_JNINativeInterface__sVC60arJvSJ44y0t2XTqiw** env, tyObject_jobject_base__jOmBXO3N5WagCUVjVXS9bwQ* obj, void* methodID, ...);
typedef N_CDECL_PTR(NI32, tyProc__xkCZtbggsh19c9cU9c4avy0bQ) (tyObject_JNINativeInterface__sVC60arJvSJ44y0t2XTqiw** env, tyObject_jobject_base__jOmBXO3N5WagCUVjVXS9bwQ* obj, void* methodID, tyObject_jvalue__QCDTMcqbrVjxIcGFMr9ai9cg* args);
typedef N_CDECL_PTR(NI64, tyProc__7g2iT9ct0rSELGwHNk0j9bmQ) (tyObject_JNINativeInterface__sVC60arJvSJ44y0t2XTqiw** env, tyObject_jobject_base__jOmBXO3N5WagCUVjVXS9bwQ* obj, void* methodID, ...);
typedef N_CDECL_PTR(NI64, tyProc__Dm9aqf3hllLiPUfPaYQrmyg) (tyObject_JNINativeInterface__sVC60arJvSJ44y0t2XTqiw** env, tyObject_jobject_base__jOmBXO3N5WagCUVjVXS9bwQ* obj, void* methodID, tyObject_jvalue__QCDTMcqbrVjxIcGFMr9ai9cg* args);
typedef N_CDECL_PTR(float, tyProc__y9bhXimZiIQn0z6jBF5f9a9aQ) (tyObject_JNINativeInterface__sVC60arJvSJ44y0t2XTqiw** env, tyObject_jobject_base__jOmBXO3N5WagCUVjVXS9bwQ* obj, void* methodID, ...);
typedef N_CDECL_PTR(float, tyProc__Ft9aYwW7WlkAUG1lYfYiwsg) (tyObject_JNINativeInterface__sVC60arJvSJ44y0t2XTqiw** env, tyObject_jobject_base__jOmBXO3N5WagCUVjVXS9bwQ* obj, void* methodID, tyObject_jvalue__QCDTMcqbrVjxIcGFMr9ai9cg* args);
typedef N_CDECL_PTR(double, tyProc__xUnV47uHdxyCxToMt3Q8Tw) (tyObject_JNINativeInterface__sVC60arJvSJ44y0t2XTqiw** env, tyObject_jobject_base__jOmBXO3N5WagCUVjVXS9bwQ* obj, void* methodID, ...);
typedef N_CDECL_PTR(double, tyProc__H7q29cexnsDarOisryxp6EA) (tyObject_JNINativeInterface__sVC60arJvSJ44y0t2XTqiw** env, tyObject_jobject_base__jOmBXO3N5WagCUVjVXS9bwQ* obj, void* methodID, tyObject_jvalue__QCDTMcqbrVjxIcGFMr9ai9cg* args);
typedef N_CDECL_PTR(void, tyProc__GhcJ30BBWy7mGl1OYwk1TQ) (tyObject_JNINativeInterface__sVC60arJvSJ44y0t2XTqiw** env, tyObject_jobject_base__jOmBXO3N5WagCUVjVXS9bwQ* obj, void* methodID, ...);
typedef N_CDECL_PTR(void, tyProc__IoTRuk1FmbmpFwkYmwOOLg) (tyObject_JNINativeInterface__sVC60arJvSJ44y0t2XTqiw** env, tyObject_jobject_base__jOmBXO3N5WagCUVjVXS9bwQ* obj, void* methodID, tyObject_jvalue__QCDTMcqbrVjxIcGFMr9ai9cg* args);
typedef N_CDECL_PTR(tyObject_jobject_base__jOmBXO3N5WagCUVjVXS9bwQ*, tyProc__7Nyg9b26IwfN3eF9asvxJyjQ) (tyObject_JNINativeInterface__sVC60arJvSJ44y0t2XTqiw** env, tyObject_jobject_base__jOmBXO3N5WagCUVjVXS9bwQ* obj, tyObject_JClasscolonObjectType___OX6jzfCvSDx9bg2iJ4S6u5Q* clazz, void* methodID, ...);
typedef N_CDECL_PTR(tyObject_jobject_base__jOmBXO3N5WagCUVjVXS9bwQ*, tyProc__19aFJrxpFMbyj7qtk9bz4aug) (tyObject_JNINativeInterface__sVC60arJvSJ44y0t2XTqiw** env, tyObject_jobject_base__jOmBXO3N5WagCUVjVXS9bwQ* obj, tyObject_JClasscolonObjectType___OX6jzfCvSDx9bg2iJ4S6u5Q* clazz, void* methodID, tyObject_jvalue__QCDTMcqbrVjxIcGFMr9ai9cg* args);
typedef N_CDECL_PTR(NU8, tyProc__J9bY9cgAnW8ccgmsFx3gMZug) (tyObject_JNINativeInterface__sVC60arJvSJ44y0t2XTqiw** env, tyObject_jobject_base__jOmBXO3N5WagCUVjVXS9bwQ* obj, tyObject_JClasscolonObjectType___OX6jzfCvSDx9bg2iJ4S6u5Q* clazz, void* methodID, ...);
typedef N_CDECL_PTR(NU8, tyProc__OFtxxZM5F3VNTX54GJ6i4A) (tyObject_JNINativeInterface__sVC60arJvSJ44y0t2XTqiw** env, tyObject_jobject_base__jOmBXO3N5WagCUVjVXS9bwQ* obj, tyObject_JClasscolonObjectType___OX6jzfCvSDx9bg2iJ4S6u5Q* clazz, void* methodID, tyObject_jvalue__QCDTMcqbrVjxIcGFMr9ai9cg* args);
typedef N_CDECL_PTR(NI8, tyProc__y3Vi5W4aX0z9aZ4iDZX79cWA) (tyObject_JNINativeInterface__sVC60arJvSJ44y0t2XTqiw** env, tyObject_jobject_base__jOmBXO3N5WagCUVjVXS9bwQ* obj, tyObject_JClasscolonObjectType___OX6jzfCvSDx9bg2iJ4S6u5Q* clazz, void* methodID, ...);
typedef N_CDECL_PTR(NI8, tyProc__TYQ6u1SyWHsM16Sf58qYjQ) (tyObject_JNINativeInterface__sVC60arJvSJ44y0t2XTqiw** env, tyObject_jobject_base__jOmBXO3N5WagCUVjVXS9bwQ* obj, tyObject_JClasscolonObjectType___OX6jzfCvSDx9bg2iJ4S6u5Q* clazz, void* methodID, tyObject_jvalue__QCDTMcqbrVjxIcGFMr9ai9cg* args);
typedef N_CDECL_PTR(NU16, tyProc__OpBC6GpFv76W9a13eeRvAxg) (tyObject_JNINativeInterface__sVC60arJvSJ44y0t2XTqiw** env, tyObject_jobject_base__jOmBXO3N5WagCUVjVXS9bwQ* obj, tyObject_JClasscolonObjectType___OX6jzfCvSDx9bg2iJ4S6u5Q* clazz, void* methodID, ...);
typedef N_CDECL_PTR(NU16, tyProc__tDXD2y1NzOhFLd2AtDZ5fw) (tyObject_JNINativeInterface__sVC60arJvSJ44y0t2XTqiw** env, tyObject_jobject_base__jOmBXO3N5WagCUVjVXS9bwQ* obj, tyObject_JClasscolonObjectType___OX6jzfCvSDx9bg2iJ4S6u5Q* clazz, void* methodID, tyObject_jvalue__QCDTMcqbrVjxIcGFMr9ai9cg* args);
typedef N_CDECL_PTR(NI16, tyProc__2sD9a8bY2lRkreVu9ch5NsbQ) (tyObject_JNINativeInterface__sVC60arJvSJ44y0t2XTqiw** env, tyObject_jobject_base__jOmBXO3N5WagCUVjVXS9bwQ* obj, tyObject_JClasscolonObjectType___OX6jzfCvSDx9bg2iJ4S6u5Q* clazz, void* methodID, ...);
typedef N_CDECL_PTR(NI16, tyProc__kLRxt2NWwWNJtDOvfW7C8A) (tyObject_JNINativeInterface__sVC60arJvSJ44y0t2XTqiw** env, tyObject_jobject_base__jOmBXO3N5WagCUVjVXS9bwQ* obj, tyObject_JClasscolonObjectType___OX6jzfCvSDx9bg2iJ4S6u5Q* clazz, void* methodID, tyObject_jvalue__QCDTMcqbrVjxIcGFMr9ai9cg* args);
typedef N_CDECL_PTR(NI32, tyProc__lvrbik67MMqeZyfUKBbAUw) (tyObject_JNINativeInterface__sVC60arJvSJ44y0t2XTqiw** env, tyObject_jobject_base__jOmBXO3N5WagCUVjVXS9bwQ* obj, tyObject_JClasscolonObjectType___OX6jzfCvSDx9bg2iJ4S6u5Q* clazz, void* methodID, ...);
typedef N_CDECL_PTR(NI32, tyProc__h9b5XpAcA9c8vchySeXxzz9cw) (tyObject_JNINativeInterface__sVC60arJvSJ44y0t2XTqiw** env, tyObject_jobject_base__jOmBXO3N5WagCUVjVXS9bwQ* obj, tyObject_JClasscolonObjectType___OX6jzfCvSDx9bg2iJ4S6u5Q* clazz, void* methodID, tyObject_jvalue__QCDTMcqbrVjxIcGFMr9ai9cg* args);
typedef N_CDECL_PTR(NI64, tyProc__f38f9bsO9cRyGpsCgHR1FCZA) (tyObject_JNINativeInterface__sVC60arJvSJ44y0t2XTqiw** env, tyObject_jobject_base__jOmBXO3N5WagCUVjVXS9bwQ* obj, tyObject_JClasscolonObjectType___OX6jzfCvSDx9bg2iJ4S6u5Q* clazz, void* methodID, ...);
typedef N_CDECL_PTR(NI64, tyProc__aYl9aBKJep8aKhMwfadpAHw) (tyObject_JNINativeInterface__sVC60arJvSJ44y0t2XTqiw** env, tyObject_jobject_base__jOmBXO3N5WagCUVjVXS9bwQ* obj, tyObject_JClasscolonObjectType___OX6jzfCvSDx9bg2iJ4S6u5Q* clazz, void* methodID, tyObject_jvalue__QCDTMcqbrVjxIcGFMr9ai9cg* args);
typedef N_CDECL_PTR(float, tyProc__CwkFdXNtFQmKc2KXYt2ung) (tyObject_JNINativeInterface__sVC60arJvSJ44y0t2XTqiw** env, tyObject_jobject_base__jOmBXO3N5WagCUVjVXS9bwQ* obj, tyObject_JClasscolonObjectType___OX6jzfCvSDx9bg2iJ4S6u5Q* clazz, void* methodID, ...);
typedef N_CDECL_PTR(float, tyProc__1VXPEsYRNNVX5lYxCNRYMw) (tyObject_JNINativeInterface__sVC60arJvSJ44y0t2XTqiw** env, tyObject_jobject_base__jOmBXO3N5WagCUVjVXS9bwQ* obj, tyObject_JClasscolonObjectType___OX6jzfCvSDx9bg2iJ4S6u5Q* clazz, void* methodID, tyObject_jvalue__QCDTMcqbrVjxIcGFMr9ai9cg* args);
typedef N_CDECL_PTR(double, tyProc__r5RRdhUbOSZE9cwdT8oa2gg) (tyObject_JNINativeInterface__sVC60arJvSJ44y0t2XTqiw** env, tyObject_jobject_base__jOmBXO3N5WagCUVjVXS9bwQ* obj, tyObject_JClasscolonObjectType___OX6jzfCvSDx9bg2iJ4S6u5Q* clazz, void* methodID, ...);
typedef N_CDECL_PTR(double, tyProc__CbVHy2WREs7HuHbKZLp3jA) (tyObject_JNINativeInterface__sVC60arJvSJ44y0t2XTqiw** env, tyObject_jobject_base__jOmBXO3N5WagCUVjVXS9bwQ* obj, tyObject_JClasscolonObjectType___OX6jzfCvSDx9bg2iJ4S6u5Q* clazz, void* methodID, tyObject_jvalue__QCDTMcqbrVjxIcGFMr9ai9cg* args);
typedef N_CDECL_PTR(void, tyProc__Os2Eb35jwxBI2IIaWEc0iw) (tyObject_JNINativeInterface__sVC60arJvSJ44y0t2XTqiw** env, tyObject_jobject_base__jOmBXO3N5WagCUVjVXS9bwQ* obj, tyObject_JClasscolonObjectType___OX6jzfCvSDx9bg2iJ4S6u5Q* clazz, void* methodID, ...);
typedef N_CDECL_PTR(void, tyProc__kEP8rOSas4sqUu8zf8xYcA) (tyObject_JNINativeInterface__sVC60arJvSJ44y0t2XTqiw** env, tyObject_jobject_base__jOmBXO3N5WagCUVjVXS9bwQ* obj, tyObject_JClasscolonObjectType___OX6jzfCvSDx9bg2iJ4S6u5Q* clazz, void* methodID, tyObject_jvalue__QCDTMcqbrVjxIcGFMr9ai9cg* args);
typedef N_CDECL_PTR(tyObject_jobject_base__jOmBXO3N5WagCUVjVXS9bwQ*, tyProc__HKl3wK9aCr9cr0LME4r9cmLIw) (tyObject_JNINativeInterface__sVC60arJvSJ44y0t2XTqiw** env, tyObject_jobject_base__jOmBXO3N5WagCUVjVXS9bwQ* obj, void* fieldId);
typedef N_CDECL_PTR(NU8, tyProc__woDGiIz55pLskIEHDrGMdQ) (tyObject_JNINativeInterface__sVC60arJvSJ44y0t2XTqiw** env, tyObject_jobject_base__jOmBXO3N5WagCUVjVXS9bwQ* obj, void* fieldId);
typedef N_CDECL_PTR(NI8, tyProc__8rYdJg9cJMxMAQ4MSkIFt1Q) (tyObject_JNINativeInterface__sVC60arJvSJ44y0t2XTqiw** env, tyObject_jobject_base__jOmBXO3N5WagCUVjVXS9bwQ* obj, void* fieldId);
typedef N_CDECL_PTR(NU16, tyProc__QwHLU6Lv1w3ycvSPx9c745w) (tyObject_JNINativeInterface__sVC60arJvSJ44y0t2XTqiw** env, tyObject_jobject_base__jOmBXO3N5WagCUVjVXS9bwQ* obj, void* fieldId);
typedef N_CDECL_PTR(NI16, tyProc__jUbiAb82AubqZuyUK5NuZw) (tyObject_JNINativeInterface__sVC60arJvSJ44y0t2XTqiw** env, tyObject_jobject_base__jOmBXO3N5WagCUVjVXS9bwQ* obj, void* fieldId);
typedef N_CDECL_PTR(NI32, tyProc__D6FiM33IqK32mlI9aNPEkJg) (tyObject_JNINativeInterface__sVC60arJvSJ44y0t2XTqiw** env, tyObject_jobject_base__jOmBXO3N5WagCUVjVXS9bwQ* obj, void* fieldId);
typedef N_CDECL_PTR(NI64, tyProc__gD9cnKXpTgMQH8d5PNQD9cPw) (tyObject_JNINativeInterface__sVC60arJvSJ44y0t2XTqiw** env, tyObject_jobject_base__jOmBXO3N5WagCUVjVXS9bwQ* obj, void* fieldId);
typedef N_CDECL_PTR(float, tyProc__SDgCYc9b09axbMEG9baj2AwXg) (tyObject_JNINativeInterface__sVC60arJvSJ44y0t2XTqiw** env, tyObject_jobject_base__jOmBXO3N5WagCUVjVXS9bwQ* obj, void* fieldId);
typedef N_CDECL_PTR(double, tyProc__yFoPhk0ty5WF3PixBEnhlg) (tyObject_JNINativeInterface__sVC60arJvSJ44y0t2XTqiw** env, tyObject_jobject_base__jOmBXO3N5WagCUVjVXS9bwQ* obj, void* fieldId);
typedef N_CDECL_PTR(void, tyProc__Q79bW7rqWtOdXHvbC0xgwpw) (tyObject_JNINativeInterface__sVC60arJvSJ44y0t2XTqiw** env, tyObject_jobject_base__jOmBXO3N5WagCUVjVXS9bwQ* obj, void* fieldId, tyObject_jobject_base__jOmBXO3N5WagCUVjVXS9bwQ* val);
typedef N_CDECL_PTR(void, tyProc__1MtrO0a1W77R9aGli57hiXA) (tyObject_JNINativeInterface__sVC60arJvSJ44y0t2XTqiw** env, tyObject_jobject_base__jOmBXO3N5WagCUVjVXS9bwQ* obj, void* fieldId, NU8 val);
typedef N_CDECL_PTR(void, tyProc__KQ6ildJWMBeSuuUfBSLrWA) (tyObject_JNINativeInterface__sVC60arJvSJ44y0t2XTqiw** env, tyObject_jobject_base__jOmBXO3N5WagCUVjVXS9bwQ* obj, void* fieldId, NI8 val);
typedef N_CDECL_PTR(void, tyProc__CMmqxHzWH24SCa9brIS5eRw) (tyObject_JNINativeInterface__sVC60arJvSJ44y0t2XTqiw** env, tyObject_jobject_base__jOmBXO3N5WagCUVjVXS9bwQ* obj, void* fieldId, NU16 val);
typedef N_CDECL_PTR(void, tyProc__rL3xq0MYJhI9cYsnvEKDr5w) (tyObject_JNINativeInterface__sVC60arJvSJ44y0t2XTqiw** env, tyObject_jobject_base__jOmBXO3N5WagCUVjVXS9bwQ* obj, void* fieldId, NI16 val);
typedef N_CDECL_PTR(void, tyProc__GQnO7229cfacsjZumf0Q9clw) (tyObject_JNINativeInterface__sVC60arJvSJ44y0t2XTqiw** env, tyObject_jobject_base__jOmBXO3N5WagCUVjVXS9bwQ* obj, void* fieldId, NI32 val);
typedef N_CDECL_PTR(void, tyProc__17Efc9ajSb8uo1XtdJADKBA) (tyObject_JNINativeInterface__sVC60arJvSJ44y0t2XTqiw** env, tyObject_jobject_base__jOmBXO3N5WagCUVjVXS9bwQ* obj, void* fieldId, NI64 val);
typedef N_CDECL_PTR(void, tyProc__PcK9a3D3iUIwc9bEYJ8ZuIsw) (tyObject_JNINativeInterface__sVC60arJvSJ44y0t2XTqiw** env, tyObject_jobject_base__jOmBXO3N5WagCUVjVXS9bwQ* obj, void* fieldId, float val);
typedef N_CDECL_PTR(void, tyProc__lqb0t9cEiwEAHi8L38RRSeg) (tyObject_JNINativeInterface__sVC60arJvSJ44y0t2XTqiw** env, tyObject_jobject_base__jOmBXO3N5WagCUVjVXS9bwQ* obj, void* fieldId, double val);
typedef N_CDECL_PTR(NU8, tyProc__oD1wB8LRTaHI59b6cGvpO0w) (tyObject_JNINativeInterface__sVC60arJvSJ44y0t2XTqiw** env, tyObject_JClasscolonObjectType___OX6jzfCvSDx9bg2iJ4S6u5Q* clazz, void* methodID, ...);
typedef N_CDECL_PTR(NU8, tyProc__X8lAGCfdjCkE2G4IRgr9c4Q) (tyObject_JNINativeInterface__sVC60arJvSJ44y0t2XTqiw** env, tyObject_JClasscolonObjectType___OX6jzfCvSDx9bg2iJ4S6u5Q* clazz, void* methodID, tyObject_jvalue__QCDTMcqbrVjxIcGFMr9ai9cg* args);
typedef N_CDECL_PTR(NI8, tyProc__aShA4zRKZgt4bb2XM4Qcsg) (tyObject_JNINativeInterface__sVC60arJvSJ44y0t2XTqiw** env, tyObject_JClasscolonObjectType___OX6jzfCvSDx9bg2iJ4S6u5Q* clazz, void* methodID, ...);
typedef N_CDECL_PTR(NI8, tyProc__HwTntITjqWFDX7udUDz03w) (tyObject_JNINativeInterface__sVC60arJvSJ44y0t2XTqiw** env, tyObject_JClasscolonObjectType___OX6jzfCvSDx9bg2iJ4S6u5Q* clazz, void* methodID, tyObject_jvalue__QCDTMcqbrVjxIcGFMr9ai9cg* args);
typedef N_CDECL_PTR(NU16, tyProc__iKhWl09a2L9axud17FyRc79ag) (tyObject_JNINativeInterface__sVC60arJvSJ44y0t2XTqiw** env, tyObject_JClasscolonObjectType___OX6jzfCvSDx9bg2iJ4S6u5Q* clazz, void* methodID, ...);
typedef N_CDECL_PTR(NU16, tyProc__OEUP0541MEkD08qEqW3tBw) (tyObject_JNINativeInterface__sVC60arJvSJ44y0t2XTqiw** env, tyObject_JClasscolonObjectType___OX6jzfCvSDx9bg2iJ4S6u5Q* clazz, void* methodID, tyObject_jvalue__QCDTMcqbrVjxIcGFMr9ai9cg* args);
typedef N_CDECL_PTR(NI16, tyProc__hYNeRrdEzkJngiBnJEiWKQ) (tyObject_JNINativeInterface__sVC60arJvSJ44y0t2XTqiw** env, tyObject_JClasscolonObjectType___OX6jzfCvSDx9bg2iJ4S6u5Q* clazz, void* methodID, ...);
typedef N_CDECL_PTR(NI16, tyProc__eimIiGQ89bNtCAVEcDJsvjw) (tyObject_JNINativeInterface__sVC60arJvSJ44y0t2XTqiw** env, tyObject_JClasscolonObjectType___OX6jzfCvSDx9bg2iJ4S6u5Q* clazz, void* methodID, tyObject_jvalue__QCDTMcqbrVjxIcGFMr9ai9cg* args);
typedef N_CDECL_PTR(NI32, tyProc__ZgsI9cTHCZU9b9cuyfkloXi7w) (tyObject_JNINativeInterface__sVC60arJvSJ44y0t2XTqiw** env, tyObject_JClasscolonObjectType___OX6jzfCvSDx9bg2iJ4S6u5Q* clazz, void* methodID, ...);
typedef N_CDECL_PTR(NI32, tyProc__pYQBnp2d7pPp7xQK9bsvhzw) (tyObject_JNINativeInterface__sVC60arJvSJ44y0t2XTqiw** env, tyObject_JClasscolonObjectType___OX6jzfCvSDx9bg2iJ4S6u5Q* clazz, void* methodID, tyObject_jvalue__QCDTMcqbrVjxIcGFMr9ai9cg* args);
typedef N_CDECL_PTR(NI64, tyProc__kciRoaFdhzsFCxtNOZGWQA) (tyObject_JNINativeInterface__sVC60arJvSJ44y0t2XTqiw** env, tyObject_JClasscolonObjectType___OX6jzfCvSDx9bg2iJ4S6u5Q* clazz, void* methodID, ...);
typedef N_CDECL_PTR(NI64, tyProc__qO1ANjb6RyH1C7D0AR9avVg) (tyObject_JNINativeInterface__sVC60arJvSJ44y0t2XTqiw** env, tyObject_JClasscolonObjectType___OX6jzfCvSDx9bg2iJ4S6u5Q* clazz, void* methodID, tyObject_jvalue__QCDTMcqbrVjxIcGFMr9ai9cg* args);
typedef N_CDECL_PTR(float, tyProc__S4qMlh9bL1ZpfswLRA9cplMQ) (tyObject_JNINativeInterface__sVC60arJvSJ44y0t2XTqiw** env, tyObject_JClasscolonObjectType___OX6jzfCvSDx9bg2iJ4S6u5Q* clazz, void* methodID, ...);
typedef N_CDECL_PTR(float, tyProc__MP9cpv9bGHOwYgo2sxF8B9a1w) (tyObject_JNINativeInterface__sVC60arJvSJ44y0t2XTqiw** env, tyObject_JClasscolonObjectType___OX6jzfCvSDx9bg2iJ4S6u5Q* clazz, void* methodID, tyObject_jvalue__QCDTMcqbrVjxIcGFMr9ai9cg* args);
typedef N_CDECL_PTR(double, tyProc__AOdcvx2hpu8FHwMz7ncFZw) (tyObject_JNINativeInterface__sVC60arJvSJ44y0t2XTqiw** env, tyObject_JClasscolonObjectType___OX6jzfCvSDx9bg2iJ4S6u5Q* clazz, void* methodID, ...);
typedef N_CDECL_PTR(double, tyProc__IiickGRlm8vONDL50qqdTw) (tyObject_JNINativeInterface__sVC60arJvSJ44y0t2XTqiw** env, tyObject_JClasscolonObjectType___OX6jzfCvSDx9bg2iJ4S6u5Q* clazz, void* methodID, tyObject_jvalue__QCDTMcqbrVjxIcGFMr9ai9cg* args);
typedef N_CDECL_PTR(void, tyProc__cWBN380E5Fl8ojwbB9bc9a3w) (tyObject_JNINativeInterface__sVC60arJvSJ44y0t2XTqiw** env, tyObject_JClasscolonObjectType___OX6jzfCvSDx9bg2iJ4S6u5Q* clazz, void* methodID, ...);
typedef N_CDECL_PTR(void, tyProc__sHkF9c3NXDPxCbGYf8WGRGQ) (tyObject_JNINativeInterface__sVC60arJvSJ44y0t2XTqiw** env, tyObject_JClasscolonObjectType___OX6jzfCvSDx9bg2iJ4S6u5Q* clazz, void* methodID, tyObject_jvalue__QCDTMcqbrVjxIcGFMr9ai9cg* args);
typedef N_CDECL_PTR(tyObject_jobject_base__jOmBXO3N5WagCUVjVXS9bwQ*, tyProc__YBy37W0c9ci9b5Q2DOLx2eaw) (tyObject_JNINativeInterface__sVC60arJvSJ44y0t2XTqiw** env, tyObject_JClasscolonObjectType___OX6jzfCvSDx9bg2iJ4S6u5Q* obj, void* fieldId);
typedef N_CDECL_PTR(NU8, tyProc__heJ5040WdyFhZw0AEVJUOA) (tyObject_JNINativeInterface__sVC60arJvSJ44y0t2XTqiw** env, tyObject_JClasscolonObjectType___OX6jzfCvSDx9bg2iJ4S6u5Q* obj, void* fieldId);
typedef N_CDECL_PTR(NI8, tyProc__Qqu9brExW2XMBElI7GiBgEg) (tyObject_JNINativeInterface__sVC60arJvSJ44y0t2XTqiw** env, tyObject_JClasscolonObjectType___OX6jzfCvSDx9bg2iJ4S6u5Q* obj, void* fieldId);
typedef N_CDECL_PTR(NU16, tyProc__cTBAW5ffLFlwmGSnN2Z7jw) (tyObject_JNINativeInterface__sVC60arJvSJ44y0t2XTqiw** env, tyObject_JClasscolonObjectType___OX6jzfCvSDx9bg2iJ4S6u5Q* obj, void* fieldId);
typedef N_CDECL_PTR(NI16, tyProc__C7mA6ssTTci9bUPqBlcY2OA) (tyObject_JNINativeInterface__sVC60arJvSJ44y0t2XTqiw** env, tyObject_JClasscolonObjectType___OX6jzfCvSDx9bg2iJ4S6u5Q* obj, void* fieldId);
typedef N_CDECL_PTR(NI32, tyProc__QiJvubdgP9aIlNSZJp0UsDg) (tyObject_JNINativeInterface__sVC60arJvSJ44y0t2XTqiw** env, tyObject_JClasscolonObjectType___OX6jzfCvSDx9bg2iJ4S6u5Q* obj, void* fieldId);
typedef N_CDECL_PTR(NI64, tyProc__9a4HemB9a9anUp8UmyV2ji6Pg) (tyObject_JNINativeInterface__sVC60arJvSJ44y0t2XTqiw** env, tyObject_JClasscolonObjectType___OX6jzfCvSDx9bg2iJ4S6u5Q* obj, void* fieldId);
typedef N_CDECL_PTR(float, tyProc__AN6iNgJutnYqiOS9cfp7Awg) (tyObject_JNINativeInterface__sVC60arJvSJ44y0t2XTqiw** env, tyObject_JClasscolonObjectType___OX6jzfCvSDx9bg2iJ4S6u5Q* obj, void* fieldId);
typedef N_CDECL_PTR(double, tyProc__28AXZfa9aHIhOKZLaIjLO2Q) (tyObject_JNINativeInterface__sVC60arJvSJ44y0t2XTqiw** env, tyObject_JClasscolonObjectType___OX6jzfCvSDx9bg2iJ4S6u5Q* obj, void* fieldId);
typedef N_CDECL_PTR(void, tyProc__mCGxu1EweGI7DCYm8BC0yg) (tyObject_JNINativeInterface__sVC60arJvSJ44y0t2XTqiw** env, tyObject_JClasscolonObjectType___OX6jzfCvSDx9bg2iJ4S6u5Q* obj, void* fieldId, tyObject_jobject_base__jOmBXO3N5WagCUVjVXS9bwQ* val);
typedef N_CDECL_PTR(void, tyProc__gD0bgFryRPOZmXVW8x0dTQ) (tyObject_JNINativeInterface__sVC60arJvSJ44y0t2XTqiw** env, tyObject_JClasscolonObjectType___OX6jzfCvSDx9bg2iJ4S6u5Q* obj, void* fieldId, NU8 val);
typedef N_CDECL_PTR(void, tyProc__XeiX37CjfbMPKhLpVU9cbug) (tyObject_JNINativeInterface__sVC60arJvSJ44y0t2XTqiw** env, tyObject_JClasscolonObjectType___OX6jzfCvSDx9bg2iJ4S6u5Q* obj, void* fieldId, NI8 val);
typedef N_CDECL_PTR(void, tyProc__imFN1Tums7HoxjCtoL9aSXQ) (tyObject_JNINativeInterface__sVC60arJvSJ44y0t2XTqiw** env, tyObject_JClasscolonObjectType___OX6jzfCvSDx9bg2iJ4S6u5Q* obj, void* fieldId, NU16 val);
typedef N_CDECL_PTR(void, tyProc__CNIFxPt7Kaqp7jkAbnKFWg) (tyObject_JNINativeInterface__sVC60arJvSJ44y0t2XTqiw** env, tyObject_JClasscolonObjectType___OX6jzfCvSDx9bg2iJ4S6u5Q* obj, void* fieldId, NI16 val);
typedef N_CDECL_PTR(void, tyProc__A1nREStm4FfgwYnHXlEukw) (tyObject_JNINativeInterface__sVC60arJvSJ44y0t2XTqiw** env, tyObject_JClasscolonObjectType___OX6jzfCvSDx9bg2iJ4S6u5Q* obj, void* fieldId, NI32 val);
typedef N_CDECL_PTR(void, tyProc__AVao9bU8Z9az6o2gWKy9bSJaA) (tyObject_JNINativeInterface__sVC60arJvSJ44y0t2XTqiw** env, tyObject_JClasscolonObjectType___OX6jzfCvSDx9bg2iJ4S6u5Q* obj, void* fieldId, NI64 val);
typedef N_CDECL_PTR(void, tyProc__h7OHQ8v9cA7PA5IGNw0R8XQ) (tyObject_JNINativeInterface__sVC60arJvSJ44y0t2XTqiw** env, tyObject_JClasscolonObjectType___OX6jzfCvSDx9bg2iJ4S6u5Q* obj, void* fieldId, float val);
typedef N_CDECL_PTR(void, tyProc__M2LrteZhe9cHbQ7aIEP67Dw) (tyObject_JNINativeInterface__sVC60arJvSJ44y0t2XTqiw** env, tyObject_JClasscolonObjectType___OX6jzfCvSDx9bg2iJ4S6u5Q* obj, void* fieldId, double val);
typedef N_CDECL_PTR(tyObject_jstringcolonObjectType___pIwvSfG0x9ct585jz20sNPg*, tyProc__6A9ckVwXiYF9cc7a6aMcJdsQ) (tyObject_JNINativeInterface__sVC60arJvSJ44y0t2XTqiw** env, NU16* unicode, NI32 len);
typedef N_CDECL_PTR(NI32, tyProc__LF8gX9cmMvFUtPIHtUMTa8w) (tyObject_JNINativeInterface__sVC60arJvSJ44y0t2XTqiw** env, tyObject_jstringcolonObjectType___pIwvSfG0x9ct585jz20sNPg* str);
typedef N_CDECL_PTR(NU16*, tyProc__QgPmBpFgYnNO1DMkZ9bkAGg) (tyObject_JNINativeInterface__sVC60arJvSJ44y0t2XTqiw** env, tyObject_jstringcolonObjectType___pIwvSfG0x9ct585jz20sNPg* str, NU8* isCopy);
typedef N_CDECL_PTR(void, tyProc__5XgIEXPkM8d1N9cw3x3iMtA) (tyObject_JNINativeInterface__sVC60arJvSJ44y0t2XTqiw** env, tyObject_jstringcolonObjectType___pIwvSfG0x9ct585jz20sNPg* str, NU16* chars);
typedef N_CDECL_PTR(tyObject_jstringcolonObjectType___pIwvSfG0x9ct585jz20sNPg*, tyProc__Et9cjhyiZpwit9acXjrn1mUQ) (tyObject_JNINativeInterface__sVC60arJvSJ44y0t2XTqiw** env, NCSTRING s);
typedef N_CDECL_PTR(NCSTRING, tyProc__MCpPI6cWjZouNCHV3dU7CQ) (tyObject_JNINativeInterface__sVC60arJvSJ44y0t2XTqiw** env, tyObject_jstringcolonObjectType___pIwvSfG0x9ct585jz20sNPg* s, NU8* isCopy);
typedef N_CDECL_PTR(void, tyProc__kpocOvZt9a7ioin7z16OCHQ) (tyObject_JNINativeInterface__sVC60arJvSJ44y0t2XTqiw** env, tyObject_jstringcolonObjectType___pIwvSfG0x9ct585jz20sNPg* s, NCSTRING cstr);
typedef N_CDECL_PTR(NI32, tyProc__RgdS2hOQ69cMIL8hjRKXu6w) (tyObject_JNINativeInterface__sVC60arJvSJ44y0t2XTqiw** env, tyObject_jarraycolonObjectType___RmEW8whL9cBQ8DcJ70FJ6lg* arr);
typedef N_CDECL_PTR(tyObject_jtypedArraycolonObjectType___a9auPON3XaqaXTm9cPqxlt9aw*, tyProc__nJ4j9cjdJLDxpitP7l9aqHFg) (tyObject_JNINativeInterface__sVC60arJvSJ44y0t2XTqiw** env, NI32 size, tyObject_JClasscolonObjectType___OX6jzfCvSDx9bg2iJ4S6u5Q* clazz, tyObject_jobject_base__jOmBXO3N5WagCUVjVXS9bwQ* init);
typedef N_CDECL_PTR(tyObject_jobject_base__jOmBXO3N5WagCUVjVXS9bwQ*, tyProc__pGxS2vufrSWYIHJmMGj3fQ) (tyObject_JNINativeInterface__sVC60arJvSJ44y0t2XTqiw** env, tyObject_jtypedArraycolonObjectType___a9auPON3XaqaXTm9cPqxlt9aw* arr, NI32 index);
typedef N_CDECL_PTR(void, tyProc__JQcWEFa1IdR1ickYsVcIiw) (tyObject_JNINativeInterface__sVC60arJvSJ44y0t2XTqiw** env, tyObject_jtypedArraycolonObjectType___a9auPON3XaqaXTm9cPqxlt9aw* arr, NI32 index, tyObject_jobject_base__jOmBXO3N5WagCUVjVXS9bwQ* val);
typedef N_CDECL_PTR(tyObject_jtypedArraycolonObjectType___a9auPON3XaqaXTm9cPqxlt9aw*, tyProc__9bFoncTBW66OFCLNoWeVSCg) (tyObject_JNINativeInterface__sVC60arJvSJ44y0t2XTqiw** env, NI32 len);
typedef N_CDECL_PTR(NU8*, tyProc__6AZK0DXmSc6a9a6aJ5bCqCA) (tyObject_JNINativeInterface__sVC60arJvSJ44y0t2XTqiw** env, tyObject_jtypedArraycolonObjectType___a9auPON3XaqaXTm9cPqxlt9aw* arr, NU8* isCopy);
typedef N_CDECL_PTR(NI8*, tyProc__dL9ab7aWwUkFbidbqfV9a8oQ) (tyObject_JNINativeInterface__sVC60arJvSJ44y0t2XTqiw** env, tyObject_jtypedArraycolonObjectType___a9auPON3XaqaXTm9cPqxlt9aw* arr, NU8* isCopy);
typedef N_CDECL_PTR(NU16*, tyProc__muIl49acnjhWotJYPVeajBA) (tyObject_JNINativeInterface__sVC60arJvSJ44y0t2XTqiw** env, tyObject_jtypedArraycolonObjectType___a9auPON3XaqaXTm9cPqxlt9aw* arr, NU8* isCopy);
typedef N_CDECL_PTR(NI16*, tyProc__t9c58USizsceKYYN9cO19aORw) (tyObject_JNINativeInterface__sVC60arJvSJ44y0t2XTqiw** env, tyObject_jtypedArraycolonObjectType___a9auPON3XaqaXTm9cPqxlt9aw* arr, NU8* isCopy);
typedef N_CDECL_PTR(NI32*, tyProc__N5uQXLwNzYZv0y9cCIsHvcg) (tyObject_JNINativeInterface__sVC60arJvSJ44y0t2XTqiw** env, tyObject_jtypedArraycolonObjectType___a9auPON3XaqaXTm9cPqxlt9aw* arr, NU8* isCopy);
typedef N_CDECL_PTR(NI64*, tyProc__WnF06Ir10800f9bxOz5uTVQ) (tyObject_JNINativeInterface__sVC60arJvSJ44y0t2XTqiw** env, tyObject_jtypedArraycolonObjectType___a9auPON3XaqaXTm9cPqxlt9aw* arr, NU8* isCopy);
typedef N_CDECL_PTR(float*, tyProc__Ov0X6R9aSYBhvAJiIEAlmYw) (tyObject_JNINativeInterface__sVC60arJvSJ44y0t2XTqiw** env, tyObject_jtypedArraycolonObjectType___a9auPON3XaqaXTm9cPqxlt9aw* arr, NU8* isCopy);
typedef N_CDECL_PTR(double*, tyProc__nipykFtMX6M7VC6f10bWLg) (tyObject_JNINativeInterface__sVC60arJvSJ44y0t2XTqiw** env, tyObject_jtypedArraycolonObjectType___a9auPON3XaqaXTm9cPqxlt9aw* arr, NU8* isCopy);
typedef N_CDECL_PTR(void, tyProc__Rc7WhipCy9bTbQ9b0P4xrsQQ) (tyObject_JNINativeInterface__sVC60arJvSJ44y0t2XTqiw** env, tyObject_jtypedArraycolonObjectType___a9auPON3XaqaXTm9cPqxlt9aw* arr, NU8* elems, NI32 mode);
typedef N_CDECL_PTR(void, tyProc__XAU2DcLhAdzy1nv9aEtYbjg) (tyObject_JNINativeInterface__sVC60arJvSJ44y0t2XTqiw** env, tyObject_jtypedArraycolonObjectType___a9auPON3XaqaXTm9cPqxlt9aw* arr, NI8* elems, NI32 mode);
typedef N_CDECL_PTR(void, tyProc__fGkrcHllXLCQwEnpxWJc6Q) (tyObject_JNINativeInterface__sVC60arJvSJ44y0t2XTqiw** env, tyObject_jtypedArraycolonObjectType___a9auPON3XaqaXTm9cPqxlt9aw* arr, NU16* elems, NI32 mode);
typedef N_CDECL_PTR(void, tyProc__K6Q5gY6pKEH3k2OOBTNMOA) (tyObject_JNINativeInterface__sVC60arJvSJ44y0t2XTqiw** env, tyObject_jtypedArraycolonObjectType___a9auPON3XaqaXTm9cPqxlt9aw* arr, NI16* elems, NI32 mode);
typedef N_CDECL_PTR(void, tyProc__ZPNdW9cm1j6gYjUhsy4XMtg) (tyObject_JNINativeInterface__sVC60arJvSJ44y0t2XTqiw** env, tyObject_jtypedArraycolonObjectType___a9auPON3XaqaXTm9cPqxlt9aw* arr, NI32* elems, NI32 mode);
typedef N_CDECL_PTR(void, tyProc__swiEo248tCfGC9cjBzXJTOQ) (tyObject_JNINativeInterface__sVC60arJvSJ44y0t2XTqiw** env, tyObject_jtypedArraycolonObjectType___a9auPON3XaqaXTm9cPqxlt9aw* arr, NI64* elems, NI32 mode);
typedef N_CDECL_PTR(void, tyProc__Oq1Qc0MmFs01vKW8oSZGuA) (tyObject_JNINativeInterface__sVC60arJvSJ44y0t2XTqiw** env, tyObject_jtypedArraycolonObjectType___a9auPON3XaqaXTm9cPqxlt9aw* arr, float* elems, NI32 mode);
typedef N_CDECL_PTR(void, tyProc__3Y6vKqGigskFWx8HPYTqdw) (tyObject_JNINativeInterface__sVC60arJvSJ44y0t2XTqiw** env, tyObject_jtypedArraycolonObjectType___a9auPON3XaqaXTm9cPqxlt9aw* arr, double* elems, NI32 mode);
typedef N_CDECL_PTR(void, tyProc__LAwGUztb9cO9bLBGW8IQ3SNw) (tyObject_JNINativeInterface__sVC60arJvSJ44y0t2XTqiw** env, tyObject_jtypedArraycolonObjectType___a9auPON3XaqaXTm9cPqxlt9aw* arr, NI32 start, NI32 len, NU8* buf);
typedef N_CDECL_PTR(void, tyProc__mKDpbYI29c4WlqDB2MdxfgA) (tyObject_JNINativeInterface__sVC60arJvSJ44y0t2XTqiw** env, tyObject_jtypedArraycolonObjectType___a9auPON3XaqaXTm9cPqxlt9aw* arr, NI32 start, NI32 len, NI8* buf);
typedef N_CDECL_PTR(void, tyProc__t1uYrmm7ze9cOkI3CNg9aoDQ) (tyObject_JNINativeInterface__sVC60arJvSJ44y0t2XTqiw** env, tyObject_jtypedArraycolonObjectType___a9auPON3XaqaXTm9cPqxlt9aw* arr, NI32 start, NI32 len, NU16* buf);
typedef N_CDECL_PTR(void, tyProc__DanC5uiFNG2p5fR3wnhsyA) (tyObject_JNINativeInterface__sVC60arJvSJ44y0t2XTqiw** env, tyObject_jtypedArraycolonObjectType___a9auPON3XaqaXTm9cPqxlt9aw* arr, NI32 start, NI32 len, NI16* buf);
typedef N_CDECL_PTR(void, tyProc__T9bQaVL9a5mecGvUVwXjAObw) (tyObject_JNINativeInterface__sVC60arJvSJ44y0t2XTqiw** env, tyObject_jtypedArraycolonObjectType___a9auPON3XaqaXTm9cPqxlt9aw* arr, NI32 start, NI32 len, NI32* buf);
typedef N_CDECL_PTR(void, tyProc__A9cYEuxDSXEcNEfOS9b4LS6g) (tyObject_JNINativeInterface__sVC60arJvSJ44y0t2XTqiw** env, tyObject_jtypedArraycolonObjectType___a9auPON3XaqaXTm9cPqxlt9aw* arr, NI32 start, NI32 len, NI64* buf);
typedef N_CDECL_PTR(void, tyProc__JISGFcDrPe4ukzFx9c4Gtng) (tyObject_JNINativeInterface__sVC60arJvSJ44y0t2XTqiw** env, tyObject_jtypedArraycolonObjectType___a9auPON3XaqaXTm9cPqxlt9aw* arr, NI32 start, NI32 len, float* buf);
typedef N_CDECL_PTR(void, tyProc__nFUlZugM0AyoFrZB9cTA0Nw) (tyObject_JNINativeInterface__sVC60arJvSJ44y0t2XTqiw** env, tyObject_jtypedArraycolonObjectType___a9auPON3XaqaXTm9cPqxlt9aw* arr, NI32 start, NI32 len, double* buf);
typedef N_CDECL_PTR(NI32, tyProc__Ls3JlIybdI7WyQv0h7aQvw) (tyObject_JNINativeInterface__sVC60arJvSJ44y0t2XTqiw** env, tyObject_JClasscolonObjectType___OX6jzfCvSDx9bg2iJ4S6u5Q* clazz, tyObject_JNINativeMethod__L6bdxAULUoPq6MmpjHdhEA* methods, NI32 nMethods);
typedef N_CDECL_PTR(NI32, tyProc__jLkNGckLHn9cVptBOZfAooQ) (tyObject_JNINativeInterface__sVC60arJvSJ44y0t2XTqiw** env, tyObject_JClasscolonObjectType___OX6jzfCvSDx9bg2iJ4S6u5Q* clazz);
typedef N_CDECL_PTR(NI32, tyProc__TVg9bE3u0Q9bJvGDsUMAe9bdA) (tyObject_JNINativeInterface__sVC60arJvSJ44y0t2XTqiw** env, tyObject_jobject_base__jOmBXO3N5WagCUVjVXS9bwQ* obj);
typedef N_CDECL_PTR(NI32, tyProc__BkSqxUGbz4le9ccVmFiLqWA) (tyObject_JNINativeInterface__sVC60arJvSJ44y0t2XTqiw** env, tyObject_JNIInvokeInterface__BH89cWeWlOVoMyLmwNaDn1Q*** vm);
typedef N_CDECL_PTR(void, tyProc__q9aElMX0QvXBI7QtBr9coUoQ) (tyObject_JNINativeInterface__sVC60arJvSJ44y0t2XTqiw** env, tyObject_jstringcolonObjectType___pIwvSfG0x9ct585jz20sNPg* str, NI32 start, NI32 len, NU16* buf);
typedef N_CDECL_PTR(void, tyProc__EmZoaX8j4dmVScEE47WYqg) (tyObject_JNINativeInterface__sVC60arJvSJ44y0t2XTqiw** env, tyObject_jstringcolonObjectType___pIwvSfG0x9ct585jz20sNPg* str, NI32 start, NI32 len, NIM_CHAR* buf);
typedef N_CDECL_PTR(void*, tyProc__vARGZmgA0gPac9cjtZwcS8A) (tyObject_JNINativeInterface__sVC60arJvSJ44y0t2XTqiw** env, tyObject_jarraycolonObjectType___RmEW8whL9cBQ8DcJ70FJ6lg* arr, NU8* isCopy);
typedef N_CDECL_PTR(void, tyProc__nkgRR9ayIkfccFJ9b7F86TTg) (tyObject_JNINativeInterface__sVC60arJvSJ44y0t2XTqiw** env, tyObject_jarraycolonObjectType___RmEW8whL9cBQ8DcJ70FJ6lg* arr, tyObject_jarraycolonObjectType___RmEW8whL9cBQ8DcJ70FJ6lg* carray, NI32 mode);
typedef N_CDECL_PTR(NU8, tyProc__jZGmvr5k2SkIymvdy9cc3KQ) (tyObject_JNINativeInterface__sVC60arJvSJ44y0t2XTqiw** env);
typedef N_CDECL_PTR(tyObject_jobject_base__jOmBXO3N5WagCUVjVXS9bwQ*, tyProc__vdZhynSxWJ2SLRDYgWv2mQ) (tyObject_JNINativeInterface__sVC60arJvSJ44y0t2XTqiw** env, void* address, NI64 capacity);
typedef N_CDECL_PTR(NI64, tyProc__iU8C9aHVwh1t8Vkm9cg0i9aCA) (tyObject_JNINativeInterface__sVC60arJvSJ44y0t2XTqiw** env, tyObject_jobject_base__jOmBXO3N5WagCUVjVXS9bwQ* buf);
typedef NI32 tyEnum_jobjectRefType__NS9asIjsWk4WC15RJ9cLEqRw;
typedef N_CDECL_PTR(tyEnum_jobjectRefType__NS9asIjsWk4WC15RJ9cLEqRw, tyProc__eaBBlBfAFM9bdMBYgLPqUNg) (tyObject_JNINativeInterface__sVC60arJvSJ44y0t2XTqiw** env, tyObject_jobject_base__jOmBXO3N5WagCUVjVXS9bwQ* obj);
struct tyObject_JNINativeInterface__sVC60arJvSJ44y0t2XTqiw {
void* reserved0;
void* reserved1;
void* reserved2;
void* reserved3;
tyProc__GTiyzoLqRtZelJ9cswu7Uow GetVersion;
tyProc__DFZxGxC0ZHf9bsKfZXJiERg DefineClass;
tyProc__em7j1GBs7VNAXMH7F9bsLzA FindClass;
tyProc__RI5QcbnF5rKJCpfe5tSkuw FromReflectedMethod;
tyProc__RI5QcbnF5rKJCpfe5tSkuw FromReflectedField;
tyProc__6GaozS8Gb3Dr0wKgiJkjkQ ToReflectedMethod;
tyProc__VWJPYSlzvPXlCZ6l3afNaA GetSuperclass;
tyProc__4CPVQiZTL1EgQ5WgxnZgfQ IsAssignableFrom;
tyProc__6GaozS8Gb3Dr0wKgiJkjkQ ToReflectedField;
tyProc__iJRdrCdAU19cu9cNbozr6Lww Throw;
tyProc__8haEwIKzLtY9ahp2OaQCKPA ThrowNew;
tyProc__PA9cdiVOg516By6pGvaQWxw ExceptionOccurred;
tyProc__TFdHnXCI9aRT5twkNf9boeCQ ExceptionDescribe;
tyProc__TFdHnXCI9aRT5twkNf9boeCQ ExceptionClear;
tyProc__zprQk8MzhuZuCVVfs7nzAQ FatalError;
tyProc__bHzJcWtjDNDl5kZqzPrAZA PushLocalFrame;
tyProc__9aa48FNC3q6O6o7JxBTqyIg PopLocalFrame;
tyProc__9aa48FNC3q6O6o7JxBTqyIg NewGlobalRef;
tyProc__g66UlTcFcTsHnYKbhCcgkQ DeleteGlobalRef;
tyProc__g66UlTcFcTsHnYKbhCcgkQ DeleteLocalRef;
tyProc__bOP4TXpDkCCdPUdwBShcHg IsSameObject;
tyProc__9aa48FNC3q6O6o7JxBTqyIg NewLocalRef;
tyProc__bHzJcWtjDNDl5kZqzPrAZA EnsureLocalCapacity;
tyProc__JzQGCKUL8PcNxxx7x5sbnQ AllocObject;
tyProc__xDGZyxEkNgFs49a0XpRnqkw NewObject;
void* NewObjectV;
tyProc__etz1nMATyY52waZ3IHPvNA NewObjectA;
tyProc__7siyna4EZ2o31AWmBTAyeQ GetObjectClass;
tyProc__Gpd9aw5aWm5w1vetb49cc9cbA IsInstanceOf;
tyProc__SJltzEg0qYejYe9c9cKJtVhg GetMethodID;
tyProc__URa83EjSMygGDUgxAj7NJA CallObjectMethod;
void* CallObjectMethodV;
tyProc__73B0l7AF0UoF9c4pPSoPTtQ CallObjectMethodA;
tyProc__BzA25CAZLkmSibqrGJQJRw CallBooleanMethod;
void* CallBooleanMethodV;
tyProc__h0HQthcF0bCGXZqy9cjpTqw CallBooleanMethodA;
tyProc__dg2OkZ2plylt11Mvu1y1rg CallByteMethod;
void* CallByteMethodV;
tyProc__t9b0wgXJxuXOxUZ7eVy24Lw CallByteMethodA;
tyProc__sukDG9ctV6DmP4uGvm9bg73Q CallCharMethod;
void* CallCharMethodV;
tyProc__WTPd4nGpA9bMpOX9cuVNdWng CallCharMethodA;
tyProc__ysjVE7f0HAax7bq4l7H2sw CallShortMethod;
void* CallShortMethodV;
tyProc__8ZgUh9bmR8aEVUx9bRfh4E4g CallShortMethodA;
tyProc__RebaplENYTeDvBpbs8enhQ CallIntMethod;
void* CallIntMethodV;
tyProc__xkCZtbggsh19c9cU9c4avy0bQ CallIntMethodA;
tyProc__7g2iT9ct0rSELGwHNk0j9bmQ CallLongMethod;
void* CallLongMethodV;
tyProc__Dm9aqf3hllLiPUfPaYQrmyg CallLongMethodA;
tyProc__y9bhXimZiIQn0z6jBF5f9a9aQ CallFloatMethod;
void* CallFloatMethodV;
tyProc__Ft9aYwW7WlkAUG1lYfYiwsg CallFloatMethodA;
tyProc__xUnV47uHdxyCxToMt3Q8Tw CallDoubleMethod;
void* CallDoubleMethodV;
tyProc__H7q29cexnsDarOisryxp6EA CallDoubleMethodA;
tyProc__GhcJ30BBWy7mGl1OYwk1TQ CallVoidMethod;
void* CallVoidMethodV;
tyProc__IoTRuk1FmbmpFwkYmwOOLg CallVoidMethodA;
tyProc__7Nyg9b26IwfN3eF9asvxJyjQ CallNonvirtualObjectMethod;
void* CallNonvirtualObjectMethodV;
tyProc__19aFJrxpFMbyj7qtk9bz4aug CallNonvirtualObjectMethodA;
tyProc__J9bY9cgAnW8ccgmsFx3gMZug CallNonvirtualBooleanMethod;
void* CallNonvirtualBooleanMethodV;
tyProc__OFtxxZM5F3VNTX54GJ6i4A CallNonvirtualBooleanMethodA;
tyProc__y3Vi5W4aX0z9aZ4iDZX79cWA CallNonvirtualByteMethod;
void* CallNonvirtualByteMethodV;
tyProc__TYQ6u1SyWHsM16Sf58qYjQ CallNonvirtualByteMethodA;
tyProc__OpBC6GpFv76W9a13eeRvAxg CallNonvirtualCharMethod;
void* CallNonvirtualCharMethodV;
tyProc__tDXD2y1NzOhFLd2AtDZ5fw CallNonvirtualCharMethodA;
tyProc__2sD9a8bY2lRkreVu9ch5NsbQ CallNonvirtualShortMethod;
void* CallNonvirtualShortMethodV;
tyProc__kLRxt2NWwWNJtDOvfW7C8A CallNonvirtualShortMethodA;
tyProc__lvrbik67MMqeZyfUKBbAUw CallNonvirtualIntMethod;
void* CallNonvirtualIntMethodV;
tyProc__h9b5XpAcA9c8vchySeXxzz9cw CallNonvirtualIntMethodA;
tyProc__f38f9bsO9cRyGpsCgHR1FCZA CallNonvirtualLongMethod;
void* CallNonvirtualLongMethodV;
tyProc__aYl9aBKJep8aKhMwfadpAHw CallNonvirtualLongMethodA;
tyProc__CwkFdXNtFQmKc2KXYt2ung CallNonvirtualFloatMethod;
void* CallNonvirtualFloatMethodV;
tyProc__1VXPEsYRNNVX5lYxCNRYMw CallNonvirtualFloatMethodA;
tyProc__r5RRdhUbOSZE9cwdT8oa2gg CallNonvirtualDoubleMethod;
void* CallNonvirtualDoubleMethodV;
tyProc__CbVHy2WREs7HuHbKZLp3jA CallNonvirtualDoubleMethodA;
tyProc__Os2Eb35jwxBI2IIaWEc0iw CallNonvirtualVoidMethod;
void* CallNonvirtualVoidMethodV;
tyProc__kEP8rOSas4sqUu8zf8xYcA CallNonvirtualVoidMethodA;
tyProc__SJltzEg0qYejYe9c9cKJtVhg GetFieldID;
tyProc__HKl3wK9aCr9cr0LME4r9cmLIw GetObjectField;
tyProc__woDGiIz55pLskIEHDrGMdQ GetBooleanField;
tyProc__8rYdJg9cJMxMAQ4MSkIFt1Q GetByteField;
tyProc__QwHLU6Lv1w3ycvSPx9c745w GetCharField;
tyProc__jUbiAb82AubqZuyUK5NuZw GetShortField;
tyProc__D6FiM33IqK32mlI9aNPEkJg GetIntField;
tyProc__gD9cnKXpTgMQH8d5PNQD9cPw GetLongField;
tyProc__SDgCYc9b09axbMEG9baj2AwXg GetFloatField;
tyProc__yFoPhk0ty5WF3PixBEnhlg GetDoubleField;
tyProc__Q79bW7rqWtOdXHvbC0xgwpw SetObjectField;
tyProc__1MtrO0a1W77R9aGli57hiXA SetBooleanField;
tyProc__KQ6ildJWMBeSuuUfBSLrWA SetByteField;
tyProc__CMmqxHzWH24SCa9brIS5eRw SetCharField;
tyProc__rL3xq0MYJhI9cYsnvEKDr5w SetShortField;
tyProc__GQnO7229cfacsjZumf0Q9clw SetIntField;
tyProc__17Efc9ajSb8uo1XtdJADKBA SetLongField;
tyProc__PcK9a3D3iUIwc9bEYJ8ZuIsw SetFloatField;
tyProc__lqb0t9cEiwEAHi8L38RRSeg SetDoubleField;
tyProc__SJltzEg0qYejYe9c9cKJtVhg GetStaticMethodID;
tyProc__xDGZyxEkNgFs49a0XpRnqkw CallStaticObjectMethod;
void* CallStaticObjectMethodV;
tyProc__etz1nMATyY52waZ3IHPvNA CallStaticObjectMethodA;
tyProc__oD1wB8LRTaHI59b6cGvpO0w CallStaticBooleanMethod;
void* CallStaticBooleanMethodV;
tyProc__X8lAGCfdjCkE2G4IRgr9c4Q CallStaticBooleanMethodA;
tyProc__aShA4zRKZgt4bb2XM4Qcsg CallStaticByteMethod;
void* CallStaticByteMethodV;
tyProc__HwTntITjqWFDX7udUDz03w CallStaticByteMethodA;
tyProc__iKhWl09a2L9axud17FyRc79ag CallStaticCharMethod;
void* CallStaticCharMethodV;
tyProc__OEUP0541MEkD08qEqW3tBw CallStaticCharMethodA;
tyProc__hYNeRrdEzkJngiBnJEiWKQ CallStaticShortMethod;
void* CallStaticShortMethodV;
tyProc__eimIiGQ89bNtCAVEcDJsvjw CallStaticShortMethodA;
tyProc__ZgsI9cTHCZU9b9cuyfkloXi7w CallStaticIntMethod;
void* CallStaticIntMethodV;
tyProc__pYQBnp2d7pPp7xQK9bsvhzw CallStaticIntMethodA;
tyProc__kciRoaFdhzsFCxtNOZGWQA CallStaticLongMethod;
void* CallStaticLongMethodV;
tyProc__qO1ANjb6RyH1C7D0AR9avVg CallStaticLongMethodA;
tyProc__S4qMlh9bL1ZpfswLRA9cplMQ CallStaticFloatMethod;
void* CallStaticFloatMethodV;
tyProc__MP9cpv9bGHOwYgo2sxF8B9a1w CallStaticFloatMethodA;
tyProc__AOdcvx2hpu8FHwMz7ncFZw CallStaticDoubleMethod;
void* CallStaticDoubleMethodV;
tyProc__IiickGRlm8vONDL50qqdTw CallStaticDoubleMethodA;
tyProc__cWBN380E5Fl8ojwbB9bc9a3w CallStaticVoidMethod;
void* CallStaticVoidMethodV;
tyProc__sHkF9c3NXDPxCbGYf8WGRGQ CallStaticVoidMethodA;
tyProc__SJltzEg0qYejYe9c9cKJtVhg GetStaticFieldID;
tyProc__YBy37W0c9ci9b5Q2DOLx2eaw GetStaticObjectField;
tyProc__heJ5040WdyFhZw0AEVJUOA GetStaticBooleanField;
tyProc__Qqu9brExW2XMBElI7GiBgEg GetStaticByteField;
tyProc__cTBAW5ffLFlwmGSnN2Z7jw GetStaticCharField;
tyProc__C7mA6ssTTci9bUPqBlcY2OA GetStaticShortField;
tyProc__QiJvubdgP9aIlNSZJp0UsDg GetStaticIntField;
tyProc__9a4HemB9a9anUp8UmyV2ji6Pg GetStaticLongField;
tyProc__AN6iNgJutnYqiOS9cfp7Awg GetStaticFloatField;
tyProc__28AXZfa9aHIhOKZLaIjLO2Q GetStaticDoubleField;
tyProc__mCGxu1EweGI7DCYm8BC0yg SetStaticObjectField;
tyProc__gD0bgFryRPOZmXVW8x0dTQ SetStaticBooleanField;
tyProc__XeiX37CjfbMPKhLpVU9cbug SetStaticByteField;
tyProc__imFN1Tums7HoxjCtoL9aSXQ SetStaticCharField;
tyProc__CNIFxPt7Kaqp7jkAbnKFWg SetStaticShortField;
tyProc__A1nREStm4FfgwYnHXlEukw SetStaticIntField;
tyProc__AVao9bU8Z9az6o2gWKy9bSJaA SetStaticLongField;
tyProc__h7OHQ8v9cA7PA5IGNw0R8XQ SetStaticFloatField;
tyProc__M2LrteZhe9cHbQ7aIEP67Dw SetStaticDoubleField;
tyProc__6A9ckVwXiYF9cc7a6aMcJdsQ NewString;
tyProc__LF8gX9cmMvFUtPIHtUMTa8w GetStringLength;
tyProc__QgPmBpFgYnNO1DMkZ9bkAGg GetStringChars;
tyProc__5XgIEXPkM8d1N9cw3x3iMtA ReleaseStringChars;
tyProc__Et9cjhyiZpwit9acXjrn1mUQ NewStringUTF;
tyProc__LF8gX9cmMvFUtPIHtUMTa8w GetStringUTFLength;
tyProc__MCpPI6cWjZouNCHV3dU7CQ GetStringUTFChars;
tyProc__kpocOvZt9a7ioin7z16OCHQ ReleaseStringUTFChars;
tyProc__RgdS2hOQ69cMIL8hjRKXu6w GetArrayLength;
tyProc__nJ4j9cjdJLDxpitP7l9aqHFg NewObjectArray;
tyProc__pGxS2vufrSWYIHJmMGj3fQ GetObjectArrayElement;
tyProc__JQcWEFa1IdR1ickYsVcIiw SetObjectArrayElement;
tyProc__9bFoncTBW66OFCLNoWeVSCg NewBooleanArray;
tyProc__9bFoncTBW66OFCLNoWeVSCg NewByteArray;
tyProc__9bFoncTBW66OFCLNoWeVSCg NewCharArray;
tyProc__9bFoncTBW66OFCLNoWeVSCg NewShortArray;
tyProc__9bFoncTBW66OFCLNoWeVSCg NewIntArray;
tyProc__9bFoncTBW66OFCLNoWeVSCg NewLongArray;
tyProc__9bFoncTBW66OFCLNoWeVSCg NewFloatArray;
tyProc__9bFoncTBW66OFCLNoWeVSCg NewDoubleArray;
tyProc__6AZK0DXmSc6a9a6aJ5bCqCA GetBooleanArrayElements;
tyProc__dL9ab7aWwUkFbidbqfV9a8oQ GetByteArrayElements;
tyProc__muIl49acnjhWotJYPVeajBA GetCharArrayElements;
tyProc__t9c58USizsceKYYN9cO19aORw GetShortArrayElements;
tyProc__N5uQXLwNzYZv0y9cCIsHvcg GetIntArrayElements;
tyProc__WnF06Ir10800f9bxOz5uTVQ GetLongArrayElements;
tyProc__Ov0X6R9aSYBhvAJiIEAlmYw GetFloatArrayElements;
tyProc__nipykFtMX6M7VC6f10bWLg GetDoubleArrayElements;
tyProc__Rc7WhipCy9bTbQ9b0P4xrsQQ ReleaseBooleanArrayElements;
tyProc__XAU2DcLhAdzy1nv9aEtYbjg ReleaseByteArrayElements;
tyProc__fGkrcHllXLCQwEnpxWJc6Q ReleaseCharArrayElements;
tyProc__K6Q5gY6pKEH3k2OOBTNMOA ReleaseShortArrayElements;
tyProc__ZPNdW9cm1j6gYjUhsy4XMtg ReleaseIntArrayElements;
tyProc__swiEo248tCfGC9cjBzXJTOQ ReleaseLongArrayElements;
tyProc__Oq1Qc0MmFs01vKW8oSZGuA ReleaseFloatArrayElements;
tyProc__3Y6vKqGigskFWx8HPYTqdw ReleaseDoubleArrayElements;
tyProc__LAwGUztb9cO9bLBGW8IQ3SNw GetBooleanArrayRegion;
tyProc__mKDpbYI29c4WlqDB2MdxfgA GetByteArrayRegion;
tyProc__t1uYrmm7ze9cOkI3CNg9aoDQ GetCharArrayRegion;
tyProc__DanC5uiFNG2p5fR3wnhsyA GetShortArrayRegion;
tyProc__T9bQaVL9a5mecGvUVwXjAObw GetIntArrayRegion;
tyProc__A9cYEuxDSXEcNEfOS9b4LS6g GetLongArrayRegion;
tyProc__JISGFcDrPe4ukzFx9c4Gtng GetFloatArrayRegion;
tyProc__nFUlZugM0AyoFrZB9cTA0Nw GetDoubleArrayRegion;
tyProc__LAwGUztb9cO9bLBGW8IQ3SNw SetBooleanArrayRegion;
tyProc__mKDpbYI29c4WlqDB2MdxfgA SetByteArrayRegion;
tyProc__t1uYrmm7ze9cOkI3CNg9aoDQ SetCharArrayRegion;
tyProc__DanC5uiFNG2p5fR3wnhsyA SetShortArrayRegion;
tyProc__T9bQaVL9a5mecGvUVwXjAObw SetIntArrayRegion;
tyProc__A9cYEuxDSXEcNEfOS9b4LS6g SetLongArrayRegion;
tyProc__JISGFcDrPe4ukzFx9c4Gtng SetFloatArrayRegion;
tyProc__nFUlZugM0AyoFrZB9cTA0Nw SetDoubleArrayRegion;
tyProc__Ls3JlIybdI7WyQv0h7aQvw RegisterNatives;
tyProc__jLkNGckLHn9cVptBOZfAooQ UnregisterNatives;
tyProc__TVg9bE3u0Q9bJvGDsUMAe9bdA MonitorEnter;
tyProc__TVg9bE3u0Q9bJvGDsUMAe9bdA MonitorExit;
tyProc__BkSqxUGbz4le9ccVmFiLqWA GetJavaVM;
tyProc__q9aElMX0QvXBI7QtBr9coUoQ GetStringRegion;
tyProc__EmZoaX8j4dmVScEE47WYqg GetStringUTFRegion;
tyProc__vARGZmgA0gPac9cjtZwcS8A GetPrimitiveArrayCritical;
tyProc__nkgRR9ayIkfccFJ9b7F86TTg ReleasePrimitiveArrayCritical;
tyProc__QgPmBpFgYnNO1DMkZ9bkAGg GetStringCritical;
tyProc__5XgIEXPkM8d1N9cw3x3iMtA ReleaseStringCritical;
tyProc__9aa48FNC3q6O6o7JxBTqyIg NewWeakGlobalRef;
tyProc__g66UlTcFcTsHnYKbhCcgkQ DeleteWeakGlobalRef;
tyProc__jZGmvr5k2SkIymvdy9cc3KQ ExceptionCheck;
tyProc__vdZhynSxWJ2SLRDYgWv2mQ NewDirectByteBuffer;
tyProc__RI5QcbnF5rKJCpfe5tSkuw GetDirectBufferAddress;
tyProc__iU8C9aHVwh1t8Vkm9cg0i9aCA GetDirectBufferCapacity;
tyProc__eaBBlBfAFM9bdMBYgLPqUNg GetObjectRefType;
};
typedef N_CDECL_PTR(NI32, tyProc__RfWjXps9aotGZt9ckVYiIncw) (tyObject_JNIInvokeInterface__BH89cWeWlOVoMyLmwNaDn1Q** vm);
typedef N_CDECL_PTR(NI32, tyProc__UtsYl9csBBW9bDeClhcQr8tw) (tyObject_JNIInvokeInterface__BH89cWeWlOVoMyLmwNaDn1Q** vm, void** penv, void* args);
typedef N_CDECL_PTR(NI32, tyProc__9cKk9brklU6KpiJr5q23rEZw) (tyObject_JNIInvokeInterface__BH89cWeWlOVoMyLmwNaDn1Q** vm, void** penv, NI32 version);
struct tyObject_JNIInvokeInterface__BH89cWeWlOVoMyLmwNaDn1Q {
void* reserved0;
void* reserved1;
void* reserved2;
tyProc__RfWjXps9aotGZt9ckVYiIncw DestroyJavaVM;
tyProc__UtsYl9csBBW9bDeClhcQr8tw AttachCurrentThread;
tyProc__RfWjXps9aotGZt9ckVYiIncw DetachCurrentThread;
tyProc__9cKk9brklU6KpiJr5q23rEZw GetEnv;
tyProc__UtsYl9csBBW9bDeClhcQr8tw AttachCurrentThreadAsDaemon;
};
struct tyObject_JClasscolonObjectType___OX6jzfCvSDx9bg2iJ4S6u5Q {
  tyObject_jobject_base__jOmBXO3N5WagCUVjVXS9bwQ Sup;
};
typedef NU8 tyEnum_TNimKind__jIBKr1ejBgsfM33Kxw4j7A;
typedef NU8 tySet_tyEnum_TNimTypeFlag__v8QUszD1sWlSIWZz7mC4bQ;
typedef N_NIMCALL_PTR(void, tyProc__ojoeKfW4VYIm36I9cpDTQIg) (void* p, NI op);
typedef N_NIMCALL_PTR(void*, tyProc__WSm2xU5ARYv9aAR4l0z9c9auQ) (void* p);
struct TNimType {
NI size;
tyEnum_TNimKind__jIBKr1ejBgsfM33Kxw4j7A kind;
tySet_tyEnum_TNimTypeFlag__v8QUszD1sWlSIWZz7mC4bQ flags;
TNimType* base;
TNimNode* node;
void* finalizer;
tyProc__ojoeKfW4VYIm36I9cpDTQIg marker;
tyProc__WSm2xU5ARYv9aAR4l0z9c9auQ deepcopy;
};
typedef NU8 tyEnum_TNimNodeKind__unfNsxrcATrufDZmpBq4HQ;
struct TNimNode {
tyEnum_TNimNodeKind__unfNsxrcATrufDZmpBq4HQ kind;
NI offset;
TNimType* typ;
NCSTRING name;
NI len;
TNimNode** sons;
};
N_LIB_EXPORT N_CDECL(tyObject_jstringcolonObjectType___pIwvSfG0x9ct585jz20sNPg*, Java_com_example_nimhellojnicallback_MainActivity_stringFromJNI)(tyObject_JNINativeInterface__sVC60arJvSJ44y0t2XTqiw** env, tyObject_jobject_base__jOmBXO3N5WagCUVjVXS9bwQ* thiz);
N_NIMCALL(NimStringDesc*, copyString)(NimStringDesc* src);
static N_INLINE(void, appendString)(NimStringDesc* dest, NimStringDesc* src);
static N_INLINE(void, copyMem__M04YC71iJg1N7gBF3HZTngsystem)(void* dest, void* source, NI size);
static N_INLINE(void, nimCopyMem)(void* dest, void* source, NI size);
N_NIMCALL(NimStringDesc*, rawNewString)(NI space);
static N_INLINE(NCSTRING, nimToCStringConv)(NimStringDesc* s);
N_LIB_EXPORT N_CDECL(NI32, JNI_OnLoad)(tyObject_JNIInvokeInterface__BH89cWeWlOVoMyLmwNaDn1Q** vmp, void* reserved);
N_NIMCALL(void, NimMain)(void);
static N_INLINE(void, nimZeroMem)(void* p, NI size);
static N_INLINE(void, nimSetMem__JE6t4x7Z3v2iVz27Nx0MRAmemory)(void* a, int v, NI size);
N_LIB_PRIVATE N_NIMCALL(void, queryRuntimeInfo__fcNuVcuZeIB42hXFDgW0Tg)(tyObject_JNINativeInterface__sVC60arJvSJ44y0t2XTqiw** envp, tyObject_jobject_base__jOmBXO3N5WagCUVjVXS9bwQ* instance);
static N_INLINE(NIM_BOOL, eqeq___aqip9cmQIuefPKdd25wuEEwsystem)(NCSTRING x, NCSTRING y);
N_NIMCALL(NimStringDesc*, nimInt64ToStr)(NI64 x);
N_LIB_EXPORT N_CDECL(void, Java_com_example_nimhellojnicallback_MainActivity_startTicks)(tyObject_JNINativeInterface__sVC60arJvSJ44y0t2XTqiw** envp, tyObject_jobject_base__jOmBXO3N5WagCUVjVXS9bwQ* instance);
N_LIB_PRIVATE N_NIMCALL(void, createThread__YTuBSuJjGBsPBvdIbGcKog)(tyObject_Thread__gtP9c8k5UKzYjkZfEnGNYRg* t, tyProc__v2sqjMSLaPokKgjL7ewsxw tp, tyObject_TickContext__1qtOMRK8IluFHXVmNYGT9cw* param);
N_LIB_PRIVATE N_NIMCALL(void, updateTicks__slpEklV9c4nxHHLJM8X9cfHA)(tyObject_TickContext__1qtOMRK8IluFHXVmNYGT9cw* pctx);
N_LIB_PRIVATE N_NIMCALL(void, sendJavaMsg__2IzprLazo1FZZl9boDcc29cA)(tyObject_JNINativeInterface__sVC60arJvSJ44y0t2XTqiw** envp, tyObject_jobject_base__jOmBXO3N5WagCUVjVXS9bwQ* instance, void* fnc, NCSTRING msg);
N_LIB_PRIVATE N_NIMCALL(NF, epochTime__9aodCrWXscOGeNVh2cpuZkw)(void);
static N_INLINE(void, pluseq___rQEZChwoSrUAnV4ouVSb6Asystem)(NF* x, NF y);
N_LIB_PRIVATE N_NIMCALL(void, nossleep)(NI milsecs);
static N_INLINE(NIM_BOOL, running__tLbz82mq5qty29b1L1CuyBgsystem)(tyObject_Thread__gtP9c8k5UKzYjkZfEnGNYRg t);
N_LIB_PRIVATE N_NIMCALL(void, failedAssertImpl__W9cjVocn1tjhW7p7xohJj6A)(NimStringDesc* msg);
N_LIB_EXPORT N_CDECL(void, Java_com_example_nimhellojnicallback_MainActivity_StopTicks)(tyObject_JNINativeInterface__sVC60arJvSJ44y0t2XTqiw** envp, tyObject_jobject_base__jOmBXO3N5WagCUVjVXS9bwQ* instance);
static N_INLINE(void, joinThread__ft4mgTO4q9au9cnuEXdyfDgwsystem)(tyObject_Thread__gtP9c8k5UKzYjkZfEnGNYRg t);
static N_INLINE(void, initStackBottomWith)(void* locals);
N_NOINLINE(void, nimGC_setStackBottom)(void* theStackBottom);
N_LIB_PRIVATE N_NIMCALL(void, systemDatInit000)(void);
N_LIB_PRIVATE N_NIMCALL(void, systemInit000)(void);
N_LIB_PRIVATE N_NIMCALL(void, stdlib_timesDatInit000)(void);
N_LIB_PRIVATE N_NIMCALL(void, stdlib_timesInit000)(void);
N_LIB_PRIVATE N_NIMCALL(void, stdlib_osDatInit000)(void);
N_LIB_PRIVATE N_NIMCALL(void, stdlib_osInit000)(void);
N_LIB_PRIVATE N_NIMCALL(void, unknown_jni_wrapperDatInit000)(void);
N_LIB_PRIVATE N_NIMCALL(void, hello_jni_callbackDatInit000)(void);
N_LIB_PRIVATE N_NIMCALL(void, NimMainModule)(void);
tyObject_TickContext__1qtOMRK8IluFHXVmNYGT9cw g_ctx__mi11Dnx3LJ5TWGXVVOSM9aQ;
TNimType NTI__1qtOMRK8IluFHXVmNYGT9cw_;
extern TNimType NTI__7FcdJ3hvYzGh4dRoLuZvAQ_;
extern TNimType NTI__rVVcaWnYpyCHyliNE2pmHQ_;
extern TNimType NTI__pPa0PUyylMh9adAOVkZUkLA_;
extern TNimType NTI__gtP9c8k5UKzYjkZfEnGNYRg_;
extern TNimType NTI__rR5Bzr1D5krxoo1NcNyeMA_;
TNimType NTI__i5xMBz9bJ9adJeXTaRrKJ9blA_;
STRING_LITERAL(TM__clAnlCXn3X5Yo6xY4Ecd9bg_2, "armeabi-v7a", 11);
STRING_LITERAL(TM__clAnlCXn3X5Yo6xY4Ecd9bg_3, "Hello from Nim native JNI! compiled for ", 40);
STRING_LITERAL(TM__clAnlCXn3X5Yo6xY4Ecd9bg_4, " .", 2);
STRING_LITERAL(TM__clAnlCXn3X5Yo6xY4Ecd9bg_6, "hello_jni_callback.nim(205, 12) `g_ctx.thrd.running` ", 53);
static N_INLINE(void, nimCopyMem)(void* dest, void* source, NI size) {	void* T1_;
	T1_ = (void*)0;
	T1_ = memcpy(dest, source, ((size_t) (size)));
}
static N_INLINE(void, copyMem__M04YC71iJg1N7gBF3HZTngsystem)(void* dest, void* source, NI size) {	nimCopyMem(dest, source, size);
}
static N_INLINE(void, appendString)(NimStringDesc* dest, NimStringDesc* src) {	{
		if (!!((src == NIM_NIL))) goto LA3_;
		copyMem__M04YC71iJg1N7gBF3HZTngsystem(((void*) ((&(*dest).data[(*dest).Sup.len]))), ((void*) ((*src).data)), ((NI) ((NI)((*src).Sup.len + ((NI) 1)))));
		(*dest).Sup.len += (*src).Sup.len;
	}
	LA3_: ;
}
static N_INLINE(NCSTRING, nimToCStringConv)(NimStringDesc* s) {	NCSTRING result;
	result = (NCSTRING)0;
	{
		NIM_BOOL T3_;
		T3_ = (NIM_BOOL)0;
		T3_ = (s == NIM_NIL);
		if (T3_) goto LA4_;
		T3_ = ((*s).Sup.len == ((NI) 0));
		LA4_: ;
		if (!T3_) goto LA5_;
		result = "";
	}
	goto LA1_;
	LA5_: ;
	{
		result = ((NCSTRING) ((*s).data));
	}
	LA1_: ;
	return result;
}
N_LIB_EXPORT N_CDECL(tyObject_jstringcolonObjectType___pIwvSfG0x9ct585jz20sNPg*, Java_com_example_nimhellojnicallback_MainActivity_stringFromJNI)(tyObject_JNINativeInterface__sVC60arJvSJ44y0t2XTqiw** env, tyObject_jobject_base__jOmBXO3N5WagCUVjVXS9bwQ* thiz) {	tyObject_jstringcolonObjectType___pIwvSfG0x9ct585jz20sNPg* result;
	NimStringDesc* ABI;
	NimStringDesc* T1_;
{	result = (tyObject_jstringcolonObjectType___pIwvSfG0x9ct585jz20sNPg*)0;
	ABI = copyString(((NimStringDesc*) &TM__clAnlCXn3X5Yo6xY4Ecd9bg_2));
	T1_ = (NimStringDesc*)0;
	T1_ = rawNewString((ABI ? ABI->Sup.len : 0) + 42);
appendString(T1_, ((NimStringDesc*) &TM__clAnlCXn3X5Yo6xY4Ecd9bg_3));
appendString(T1_, ABI);
appendString(T1_, ((NimStringDesc*) &TM__clAnlCXn3X5Yo6xY4Ecd9bg_4));
	result = (*(*env)).NewStringUTF(env, nimToCStringConv(T1_));
	goto BeforeRet_;
	}BeforeRet_: ;
	return result;
}
static N_INLINE(void, nimSetMem__JE6t4x7Z3v2iVz27Nx0MRAmemory)(void* a, int v, NI size) {	void* T1_;
	T1_ = (void*)0;
	T1_ = memset(a, v, ((size_t) (size)));
}
static N_INLINE(void, nimZeroMem)(void* p, NI size) {	nimSetMem__JE6t4x7Z3v2iVz27Nx0MRAmemory(p, ((int) 0), size);
}
static N_INLINE(NIM_BOOL, eqeq___aqip9cmQIuefPKdd25wuEEwsystem)(NCSTRING x, NCSTRING y) {	NIM_BOOL result;
	result = (NIM_BOOL)0;
	{
		if (!(((void*) (x)) == ((void*) (y)))) goto LA3_;
		result = NIM_TRUE;
	}
	goto LA1_;
	LA3_: ;
	{
		NIM_BOOL T6_;
		T6_ = (NIM_BOOL)0;
		T6_ = (x == 0);
		if (T6_) goto LA7_;
		T6_ = (y == 0);
		LA7_: ;
		if (!T6_) goto LA8_;
		result = NIM_FALSE;
	}
	goto LA1_;
	LA8_: ;
	{
		int T11_;
		T11_ = (int)0;
		T11_ = strcmp(x, y);
		result = (T11_ == ((NI32) 0));
	}
	LA1_: ;
	return result;
}
N_LIB_PRIVATE N_NIMCALL(void, queryRuntimeInfo__fcNuVcuZeIB42hXFDgW0Tg)(tyObject_JNINativeInterface__sVC60arJvSJ44y0t2XTqiw** envp, tyObject_jobject_base__jOmBXO3N5WagCUVjVXS9bwQ* instance) {	void* versionFunc;
	tyObject_jstringcolonObjectType___pIwvSfG0x9ct585jz20sNPg* buildVersion;
	tyObject_jobject_base__jOmBXO3N5WagCUVjVXS9bwQ* T6_;
	NCSTRING version;
	int T13_;
	tyObject_jobject_base__jOmBXO3N5WagCUVjVXS9bwQ* T14_;
	void* memFunc;
	NI64 result;
	NimStringDesc* T20_;
	int T21_;
{	versionFunc = (*(*envp)).GetStaticMethodID(envp, g_ctx__mi11Dnx3LJ5TWGXVVOSM9aQ.jniHelperClz, "getBuildVersion", "()Ljava/lang/String;");
	{
		int T5_;
		if (!(versionFunc == NIM_NIL)) goto LA3_;
		T5_ = (int)0;
		T5_ = __android_log_print(((int) 6), "nim-hello-jniCallback", "Failed to retrieve getBuildVersion() methodID @ line %d", ((NI32) 90));
		goto BeforeRet_;
	}
	LA3_: ;
	T6_ = (tyObject_jobject_base__jOmBXO3N5WagCUVjVXS9bwQ*)0;
	T6_ = (*(*envp)).CallStaticObjectMethod(envp, g_ctx__mi11Dnx3LJ5TWGXVVOSM9aQ.jniHelperClz, versionFunc);
	buildVersion = ((tyObject_jstringcolonObjectType___pIwvSfG0x9ct585jz20sNPg*) (T6_));
	version = (*(*envp)).GetStringUTFChars(envp, buildVersion, NIM_NIL);
	{
		NIM_BOOL T9_;
		int T12_;
		T9_ = (NIM_BOOL)0;
		T9_ = eqeq___aqip9cmQIuefPKdd25wuEEwsystem(version, NIM_NIL);
		if (!T9_) goto LA10_;
		T12_ = (int)0;
		T12_ = __android_log_print(((int) 6), "nim-hello-jniCallback", "Unable to get version string @ line %d", ((NI32) 95));
		goto BeforeRet_;
	}
	LA10_: ;
	T13_ = (int)0;
	T13_ = __android_log_print(((int) 4), "nim-hello-jniCallback", "Android Version - %s", version);
	(*(*envp)).ReleaseStringUTFChars(envp, buildVersion, version);
	T14_ = (tyObject_jobject_base__jOmBXO3N5WagCUVjVXS9bwQ*)0;
	T14_ = &buildVersion->Sup;
	(*(*envp)).DeleteLocalRef(envp, T14_);
	memFunc = (*(*envp)).GetMethodID(envp, g_ctx__mi11Dnx3LJ5TWGXVVOSM9aQ.jniHelperClz, "getRuntimeMemorySize", "()J");
	{
		int T19_;
		if (!(memFunc == NIM_NIL)) goto LA17_;
		T19_ = (int)0;
		T19_ = __android_log_print(((int) 6), "nim-hello-jniCallback", "Failed to retrieve getRuntimeMemorySize() methodID @ line %d", ((NI32) 106));
		goto BeforeRet_;
	}
	LA17_: ;
	result = (*(*envp)).CallLongMethod(envp, instance, memFunc);
	T20_ = (NimStringDesc*)0;
	T20_ = nimInt64ToStr(result);
	T21_ = (int)0;
	T21_ = __android_log_print(((int) 4), "nim-hello-jniCallback", "Runtime free memory size: %s", nimToCStringConv(T20_));
	}BeforeRet_: ;
}
N_LIB_EXPORT N_CDECL(NI32, JNI_OnLoad)(tyObject_JNIInvokeInterface__BH89cWeWlOVoMyLmwNaDn1Q** vmp, void* reserved) {	NI32 result;
	tyObject_JNINativeInterface__sVC60arJvSJ44y0t2XTqiw** envp;
	tyObject_JClasscolonObjectType___OX6jzfCvSDx9bg2iJ4S6u5Q* clz;
	tyObject_jobject_base__jOmBXO3N5WagCUVjVXS9bwQ* T6_;
	tyObject_jobject_base__jOmBXO3N5WagCUVjVXS9bwQ* T7_;
	void* jniHelperCtor;
	tyObject_jobject_base__jOmBXO3N5WagCUVjVXS9bwQ* handler;
{	result = (NI32)0;
	NimMain();
	envp = (tyObject_JNINativeInterface__sVC60arJvSJ44y0t2XTqiw**)0;
	nimZeroMem((void*)(&g_ctx__mi11Dnx3LJ5TWGXVVOSM9aQ), sizeof(tyObject_TickContext__1qtOMRK8IluFHXVmNYGT9cw));
	g_ctx__mi11Dnx3LJ5TWGXVVOSM9aQ.javaVM = vmp;
	{
		NI32 T3_;
		T3_ = (NI32)0;
		T3_ = (*(*vmp)).GetEnv(vmp, ((void**) (&envp)), ((NI32) 65542));
		if (!!((T3_ == ((NI32) 0)))) goto LA4_;
		result = ((NI32) -1);
		goto BeforeRet_;
	}
	LA4_: ;
	clz = (*(*envp)).FindClass(envp, "com/example/nimhellojnicallback/JniHandler");
	T6_ = (tyObject_jobject_base__jOmBXO3N5WagCUVjVXS9bwQ*)0;
	T6_ = &clz->Sup;
	T7_ = (tyObject_jobject_base__jOmBXO3N5WagCUVjVXS9bwQ*)0;
	T7_ = (*(*envp)).NewGlobalRef(envp, T6_);
	g_ctx__mi11Dnx3LJ5TWGXVVOSM9aQ.jniHelperClz = ((tyObject_JClasscolonObjectType___OX6jzfCvSDx9bg2iJ4S6u5Q*) (T7_));
	jniHelperCtor = (*(*envp)).GetMethodID(envp, g_ctx__mi11Dnx3LJ5TWGXVVOSM9aQ.jniHelperClz, "<init>", "()V");
	handler = (*(*envp)).NewObject(envp, g_ctx__mi11Dnx3LJ5TWGXVVOSM9aQ.jniHelperClz, jniHelperCtor);
	g_ctx__mi11Dnx3LJ5TWGXVVOSM9aQ.jniHelperObj = (*(*envp)).NewGlobalRef(envp, handler);
	queryRuntimeInfo__fcNuVcuZeIB42hXFDgW0Tg(envp, g_ctx__mi11Dnx3LJ5TWGXVVOSM9aQ.jniHelperObj);
	g_ctx__mi11Dnx3LJ5TWGXVVOSM9aQ.done = ((NI) 0);
	g_ctx__mi11Dnx3LJ5TWGXVVOSM9aQ.mainActivityObj = NIM_NIL;
	result = ((NI32) 65542);
	goto BeforeRet_;
	}BeforeRet_: ;
	return result;
}
N_LIB_PRIVATE N_NIMCALL(void, sendJavaMsg__2IzprLazo1FZZl9boDcc29cA)(tyObject_JNINativeInterface__sVC60arJvSJ44y0t2XTqiw** envp, tyObject_jobject_base__jOmBXO3N5WagCUVjVXS9bwQ* instance, void* fnc, NCSTRING msg) {	tyObject_jstringcolonObjectType___pIwvSfG0x9ct585jz20sNPg* javaMsg;
	tyObject_jobject_base__jOmBXO3N5WagCUVjVXS9bwQ* T1_;
	javaMsg = (*(*envp)).NewStringUTF(envp, msg);
	(*(*envp)).CallVoidMethod(envp, instance, fnc, javaMsg);
	T1_ = (tyObject_jobject_base__jOmBXO3N5WagCUVjVXS9bwQ*)0;
	T1_ = &javaMsg->Sup;
	(*(*envp)).DeleteLocalRef(envp, T1_);
}
static N_INLINE(void, pluseq___rQEZChwoSrUAnV4ouVSb6Asystem)(NF* x, NF y) {	(*x) = ((NF)((*x)) + (NF)(y));
}
N_LIB_PRIVATE N_NIMCALL(void, updateTicks__slpEklV9c4nxHHLJM8X9cfHA)(tyObject_TickContext__1qtOMRK8IluFHXVmNYGT9cw* pctx) {	tyObject_JNIInvokeInterface__BH89cWeWlOVoMyLmwNaDn1Q** javaVM;
	tyObject_JNINativeInterface__sVC60arJvSJ44y0t2XTqiw** envp;
	NI32 res;
	void* statusId;
	void* timerId;
	NF nextTime;
	NF T10_;
	NI32 T24_;
{	javaVM = (*pctx).javaVM;
	envp = (tyObject_JNINativeInterface__sVC60arJvSJ44y0t2XTqiw**)0;
	res = (*(*javaVM)).GetEnv(javaVM, ((void**) (&envp)), ((NI32) 65542));
	{
		if (!!((res == ((NI32) 0)))) goto LA3_;
		res = (*(*javaVM)).AttachCurrentThread(javaVM, ((void**) (&envp)), NIM_NIL);
		{
			int T9_;
			if (!!((res == ((NI32) 0)))) goto LA7_;
			T9_ = (int)0;
			T9_ = __android_log_print(((int) 6), "nim-hello-jniCallback", "Failed to AttachCurrentThread, ErrorCode = %d", res);
			goto BeforeRet_;
		}
		LA7_: ;
	}
	LA3_: ;
	statusId = (*(*envp)).GetMethodID(envp, (*pctx).jniHelperClz, "updateStatus", "(Ljava/lang/String;)V");
	sendJavaMsg__2IzprLazo1FZZl9boDcc29cA(envp, (*pctx).jniHelperObj, statusId, "TickerThread status: initializing...");
	timerId = (*(*envp)).GetMethodID(envp, (*pctx).mainActivityClz, "updateTimer", "()V");
	sendJavaMsg__2IzprLazo1FZZl9boDcc29cA(envp, (*pctx).jniHelperObj, statusId, "TickerThread status: start ticking ...");
	T10_ = (NF)0;
	T10_ = epochTime__9aodCrWXscOGeNVh2cpuZkw();
	nextTime = ((NF)(T10_) + (NF)(1.0000000000000000e+000));
	{
		while (1) {
			NF leftTime;
			NF T17_;
			{
				if (!!(((*pctx).done == ((NI) 0)))) goto LA15_;
				goto LA11;
			}
			LA15_: ;
			(*(*envp)).CallVoidMethod(envp, (*pctx).mainActivityObj, timerId);
			T17_ = (NF)0;
			T17_ = epochTime__9aodCrWXscOGeNVh2cpuZkw();
			leftTime = ((NF)(nextTime) - (NF)(T17_));
			pluseq___rQEZChwoSrUAnV4ouVSb6Asystem((&nextTime), 1.0000000000000000e+000);
			{
				NF T22_;
				if (!(0.0 <= leftTime)) goto LA20_;
				T22_ = (NF)0;
				T22_ = ceil(((NF)(leftTime) * (NF)(1.0000000000000000e+003)));
				nossleep(((NI) (T22_)));
			}
			goto LA18_;
			LA20_: ;
			{
				sendJavaMsg__2IzprLazo1FZZl9boDcc29cA(envp, (*pctx).jniHelperObj, statusId, "TickerThread error: processing too long!");
				goto LA11;
			}
			LA18_: ;
		}
	} LA11: ;
	sendJavaMsg__2IzprLazo1FZZl9boDcc29cA(envp, (*pctx).jniHelperObj, statusId, "TickerThread status: ticking stopped");
	T24_ = (NI32)0;
	T24_ = (*(*javaVM)).DetachCurrentThread(javaVM);
	(void)(T24_);
	}BeforeRet_: ;
}
static N_INLINE(NIM_BOOL, running__tLbz82mq5qty29b1L1CuyBgsystem)(tyObject_Thread__gtP9c8k5UKzYjkZfEnGNYRg t) {	NIM_BOOL result;
	result = (NIM_BOOL)0;
	result = !((t.dataFn == NIM_NIL));
	return result;
}
N_LIB_EXPORT N_CDECL(void, Java_com_example_nimhellojnicallback_MainActivity_startTicks)(tyObject_JNINativeInterface__sVC60arJvSJ44y0t2XTqiw** envp, tyObject_jobject_base__jOmBXO3N5WagCUVjVXS9bwQ* instance) {	tyObject_JClasscolonObjectType___OX6jzfCvSDx9bg2iJ4S6u5Q* clz;
	tyObject_jobject_base__jOmBXO3N5WagCUVjVXS9bwQ* T1_;
	tyObject_jobject_base__jOmBXO3N5WagCUVjVXS9bwQ* T2_;
	clz = (*(*envp)).GetObjectClass(envp, instance);
	T1_ = (tyObject_jobject_base__jOmBXO3N5WagCUVjVXS9bwQ*)0;
	T1_ = &clz->Sup;
	T2_ = (tyObject_jobject_base__jOmBXO3N5WagCUVjVXS9bwQ*)0;
	T2_ = (*(*envp)).NewGlobalRef(envp, T1_);
	g_ctx__mi11Dnx3LJ5TWGXVVOSM9aQ.mainActivityClz = ((tyObject_JClasscolonObjectType___OX6jzfCvSDx9bg2iJ4S6u5Q*) (T2_));
	g_ctx__mi11Dnx3LJ5TWGXVVOSM9aQ.mainActivityObj = (*(*envp)).NewGlobalRef(envp, instance);
	g_ctx__mi11Dnx3LJ5TWGXVVOSM9aQ.done = ((NI) 0);
	createThread__YTuBSuJjGBsPBvdIbGcKog((&g_ctx__mi11Dnx3LJ5TWGXVVOSM9aQ.thrd), updateTicks__slpEklV9c4nxHHLJM8X9cfHA, (&g_ctx__mi11Dnx3LJ5TWGXVVOSM9aQ));
	{
		NIM_BOOL T5_;
		T5_ = (NIM_BOOL)0;
		T5_ = running__tLbz82mq5qty29b1L1CuyBgsystem(g_ctx__mi11Dnx3LJ5TWGXVVOSM9aQ.thrd);
		if (!!(T5_)) goto LA6_;
		failedAssertImpl__W9cjVocn1tjhW7p7xohJj6A(((NimStringDesc*) &TM__clAnlCXn3X5Yo6xY4Ecd9bg_6));
	}
	LA6_: ;
}
static N_INLINE(void, joinThread__ft4mgTO4q9au9cnuEXdyfDgwsystem)(tyObject_Thread__gtP9c8k5UKzYjkZfEnGNYRg t) {	int T1_;
	T1_ = (int)0;
	T1_ = pthread_join(t.sys, NIM_NIL);
	(void)(T1_);
}
N_LIB_EXPORT N_CDECL(void, Java_com_example_nimhellojnicallback_MainActivity_StopTicks)(tyObject_JNINativeInterface__sVC60arJvSJ44y0t2XTqiw** envp, tyObject_jobject_base__jOmBXO3N5WagCUVjVXS9bwQ* instance) {	tyObject_jobject_base__jOmBXO3N5WagCUVjVXS9bwQ* T1_;
	g_ctx__mi11Dnx3LJ5TWGXVVOSM9aQ.done = ((NI) 1);
	joinThread__ft4mgTO4q9au9cnuEXdyfDgwsystem(g_ctx__mi11Dnx3LJ5TWGXVVOSM9aQ.thrd);
	T1_ = (tyObject_jobject_base__jOmBXO3N5WagCUVjVXS9bwQ*)0;
	T1_ = &g_ctx__mi11Dnx3LJ5TWGXVVOSM9aQ.mainActivityClz->Sup;
	(*(*envp)).DeleteGlobalRef(envp, T1_);
	(*(*envp)).DeleteGlobalRef(envp, g_ctx__mi11Dnx3LJ5TWGXVVOSM9aQ.mainActivityObj);
	g_ctx__mi11Dnx3LJ5TWGXVVOSM9aQ.mainActivityClz = NIM_NIL;
	g_ctx__mi11Dnx3LJ5TWGXVVOSM9aQ.mainActivityObj = NIM_NIL;
}
static N_INLINE(void, initStackBottomWith)(void* locals) {	nimGC_setStackBottom(locals);
}

void PreMainInner(void) {
	stdlib_timesInit000();
	stdlib_osInit000();
}

int cmdCount;
char** cmdLine;
char** gEnv;
void PreMain(void) {
	void (*volatile inner)(void);
	inner = PreMainInner;
	systemDatInit000();
	initStackBottomWith((void *)&inner);
	systemInit000();
	stdlib_timesDatInit000();
	stdlib_osDatInit000();
	unknown_jni_wrapperDatInit000();
	hello_jni_callbackDatInit000();
	(*inner)();
}

N_CDECL(void, NimMainInner)(void) {
	NimMainModule();
}

N_CDECL(void, NimMain)(void) {
	void (*volatile inner)(void);
	PreMain();
	inner = NimMainInner;
	initStackBottomWith((void *)&inner);
	(*inner)();
}

N_LIB_PRIVATE N_NIMCALL(void, NimMainModule)(void) {
{
}
}

N_LIB_PRIVATE N_NIMCALL(void, hello_jni_callbackDatInit000)(void) {
static TNimNode* TM__clAnlCXn3X5Yo6xY4Ecd9bg_5_7[7];
static TNimNode TM__clAnlCXn3X5Yo6xY4Ecd9bg_0[8];
NTI__1qtOMRK8IluFHXVmNYGT9cw_.size = sizeof(tyObject_TickContext__1qtOMRK8IluFHXVmNYGT9cw);
NTI__1qtOMRK8IluFHXVmNYGT9cw_.kind = 18;
NTI__1qtOMRK8IluFHXVmNYGT9cw_.base = 0;
NTI__1qtOMRK8IluFHXVmNYGT9cw_.flags = 3;
TM__clAnlCXn3X5Yo6xY4Ecd9bg_5_7[0] = &TM__clAnlCXn3X5Yo6xY4Ecd9bg_0[1];
TM__clAnlCXn3X5Yo6xY4Ecd9bg_0[1].kind = 1;
TM__clAnlCXn3X5Yo6xY4Ecd9bg_0[1].offset = offsetof(tyObject_TickContext__1qtOMRK8IluFHXVmNYGT9cw, javaVM);
TM__clAnlCXn3X5Yo6xY4Ecd9bg_0[1].typ = (&NTI__7FcdJ3hvYzGh4dRoLuZvAQ_);
TM__clAnlCXn3X5Yo6xY4Ecd9bg_0[1].name = "javaVM";
TM__clAnlCXn3X5Yo6xY4Ecd9bg_5_7[1] = &TM__clAnlCXn3X5Yo6xY4Ecd9bg_0[2];
TM__clAnlCXn3X5Yo6xY4Ecd9bg_0[2].kind = 1;
TM__clAnlCXn3X5Yo6xY4Ecd9bg_0[2].offset = offsetof(tyObject_TickContext__1qtOMRK8IluFHXVmNYGT9cw, jniHelperClz);
TM__clAnlCXn3X5Yo6xY4Ecd9bg_0[2].typ = (&NTI__rVVcaWnYpyCHyliNE2pmHQ_);
TM__clAnlCXn3X5Yo6xY4Ecd9bg_0[2].name = "jniHelperClz";
TM__clAnlCXn3X5Yo6xY4Ecd9bg_5_7[2] = &TM__clAnlCXn3X5Yo6xY4Ecd9bg_0[3];
TM__clAnlCXn3X5Yo6xY4Ecd9bg_0[3].kind = 1;
TM__clAnlCXn3X5Yo6xY4Ecd9bg_0[3].offset = offsetof(tyObject_TickContext__1qtOMRK8IluFHXVmNYGT9cw, jniHelperObj);
TM__clAnlCXn3X5Yo6xY4Ecd9bg_0[3].typ = (&NTI__pPa0PUyylMh9adAOVkZUkLA_);
TM__clAnlCXn3X5Yo6xY4Ecd9bg_0[3].name = "jniHelperObj";
TM__clAnlCXn3X5Yo6xY4Ecd9bg_5_7[3] = &TM__clAnlCXn3X5Yo6xY4Ecd9bg_0[4];
TM__clAnlCXn3X5Yo6xY4Ecd9bg_0[4].kind = 1;
TM__clAnlCXn3X5Yo6xY4Ecd9bg_0[4].offset = offsetof(tyObject_TickContext__1qtOMRK8IluFHXVmNYGT9cw, mainActivityClz);
TM__clAnlCXn3X5Yo6xY4Ecd9bg_0[4].typ = (&NTI__rVVcaWnYpyCHyliNE2pmHQ_);
TM__clAnlCXn3X5Yo6xY4Ecd9bg_0[4].name = "mainActivityClz";
TM__clAnlCXn3X5Yo6xY4Ecd9bg_5_7[4] = &TM__clAnlCXn3X5Yo6xY4Ecd9bg_0[5];
TM__clAnlCXn3X5Yo6xY4Ecd9bg_0[5].kind = 1;
TM__clAnlCXn3X5Yo6xY4Ecd9bg_0[5].offset = offsetof(tyObject_TickContext__1qtOMRK8IluFHXVmNYGT9cw, mainActivityObj);
TM__clAnlCXn3X5Yo6xY4Ecd9bg_0[5].typ = (&NTI__pPa0PUyylMh9adAOVkZUkLA_);
TM__clAnlCXn3X5Yo6xY4Ecd9bg_0[5].name = "mainActivityObj";
TM__clAnlCXn3X5Yo6xY4Ecd9bg_5_7[5] = &TM__clAnlCXn3X5Yo6xY4Ecd9bg_0[6];
TM__clAnlCXn3X5Yo6xY4Ecd9bg_0[6].kind = 1;
TM__clAnlCXn3X5Yo6xY4Ecd9bg_0[6].offset = offsetof(tyObject_TickContext__1qtOMRK8IluFHXVmNYGT9cw, thrd);
TM__clAnlCXn3X5Yo6xY4Ecd9bg_0[6].typ = (&NTI__gtP9c8k5UKzYjkZfEnGNYRg_);
TM__clAnlCXn3X5Yo6xY4Ecd9bg_0[6].name = "thrd";
TM__clAnlCXn3X5Yo6xY4Ecd9bg_5_7[6] = &TM__clAnlCXn3X5Yo6xY4Ecd9bg_0[7];
TM__clAnlCXn3X5Yo6xY4Ecd9bg_0[7].kind = 1;
TM__clAnlCXn3X5Yo6xY4Ecd9bg_0[7].offset = offsetof(tyObject_TickContext__1qtOMRK8IluFHXVmNYGT9cw, done);
TM__clAnlCXn3X5Yo6xY4Ecd9bg_0[7].typ = (&NTI__rR5Bzr1D5krxoo1NcNyeMA_);
TM__clAnlCXn3X5Yo6xY4Ecd9bg_0[7].name = "done";
TM__clAnlCXn3X5Yo6xY4Ecd9bg_0[0].len = 7; TM__clAnlCXn3X5Yo6xY4Ecd9bg_0[0].kind = 2; TM__clAnlCXn3X5Yo6xY4Ecd9bg_0[0].sons = &TM__clAnlCXn3X5Yo6xY4Ecd9bg_5_7[0];
NTI__1qtOMRK8IluFHXVmNYGT9cw_.node = &TM__clAnlCXn3X5Yo6xY4Ecd9bg_0[0];
NTI__i5xMBz9bJ9adJeXTaRrKJ9blA_.size = sizeof(tyObject_TickContext__1qtOMRK8IluFHXVmNYGT9cw*);
NTI__i5xMBz9bJ9adJeXTaRrKJ9blA_.kind = 21;
NTI__i5xMBz9bJ9adJeXTaRrKJ9blA_.base = (&NTI__1qtOMRK8IluFHXVmNYGT9cw_);
NTI__i5xMBz9bJ9adJeXTaRrKJ9blA_.flags = 3;
}

